// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/warehouse/v1/models.proto

package warehouse_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Warehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StoreId       *int64                 `protobuf:"varint,10,opt,name=store_id,json=storeId,proto3,oneof" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_api_warehouse_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Warehouse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warehouse) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Warehouse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Warehouse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Warehouse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Warehouse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Warehouse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Warehouse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Warehouse) GetStoreId() int64 {
	if x != nil && x.StoreId != nil {
		return *x.StoreId
	}
	return 0
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WarehouseId   int64                  `protobuf:"varint,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MinQuantity   string                 `protobuf:"bytes,6,opt,name=min_quantity,json=minQuantity,proto3" json:"min_quantity,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_api_warehouse_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *StockItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StockItem) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *StockItem) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *StockItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StockItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *StockItem) GetMinQuantity() string {
	if x != nil {
		return x.MinQuantity
	}
	return ""
}

func (x *StockItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type StockMovement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WarehouseId    int64                  `protobuf:"varint,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ProductId      int64                  `protobuf:"varint,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity       string                 `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CounterpartyId *int64                 `protobuf:"varint,7,opt,name=counterparty_id,json=counterpartyId,proto3,oneof" json:"counterparty_id,omitempty"`
	Reason         *string                `protobuf:"bytes,8,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	CreatedBy      int64                  `protobuf:"varint,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StockMovement) Reset() {
	*x = StockMovement{}
	mi := &file_api_warehouse_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockMovement) ProtoMessage() {}

func (x *StockMovement) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockMovement.ProtoReflect.Descriptor instead.
func (*StockMovement) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *StockMovement) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StockMovement) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *StockMovement) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *StockMovement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StockMovement) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StockMovement) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *StockMovement) GetCounterpartyId() int64 {
	if x != nil && x.CounterpartyId != nil {
		return *x.CounterpartyId
	}
	return 0
}

func (x *StockMovement) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *StockMovement) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *StockMovement) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WarehouseId   int64                  `protobuf:"varint,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *string                `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	Items         []*InventoryItem       `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_api_warehouse_v1_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *Inventory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Inventory) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Inventory) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *Inventory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Inventory) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Inventory) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Inventory) GetCompletedAt() string {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return ""
}

func (x *Inventory) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InventoryId   int64                  `protobuf:"varint,2,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ExpectedQty   string                 `protobuf:"bytes,4,opt,name=expected_qty,json=expectedQty,proto3" json:"expected_qty,omitempty"`
	ActualQty     *string                `protobuf:"bytes,5,opt,name=actual_qty,json=actualQty,proto3,oneof" json:"actual_qty,omitempty"`
	Difference    *string                `protobuf:"bytes,6,opt,name=difference,proto3,oneof" json:"difference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_api_warehouse_v1_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_models_proto_rawDescGZIP(), []int{4}
}

func (x *InventoryItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InventoryItem) GetInventoryId() int64 {
	if x != nil {
		return x.InventoryId
	}
	return 0
}

func (x *InventoryItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *InventoryItem) GetExpectedQty() string {
	if x != nil {
		return x.ExpectedQty
	}
	return ""
}

func (x *InventoryItem) GetActualQty() string {
	if x != nil && x.ActualQty != nil {
		return *x.ActualQty
	}
	return ""
}

func (x *InventoryItem) GetDifference() string {
	if x != nil && x.Difference != nil {
		return *x.Difference
	}
	return ""
}

var File_api_warehouse_v1_models_proto protoreflect.FileDescriptor

const file_api_warehouse_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/warehouse/v1/models.proto\x12\fwarehouse.v1\"\xa4\x02\n" +
	"\tWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x1e\n" +
	"\bstore_id\x18\n" +
	" \x01(\x03H\x00R\astoreId\x88\x01\x01B\v\n" +
	"\t_store_id\"\xd8\x01\n" +
	"\tStockItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\x03R\vwarehouseId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12!\n" +
	"\fmin_quantity\x18\x06 \x01(\tR\vminQuantity\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xd6\x02\n" +
	"\rStockMovement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\x03R\vwarehouseId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\x12,\n" +
	"\x0fcounterparty_id\x18\a \x01(\x03H\x00R\x0ecounterpartyId\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\b \x01(\tH\x01R\x06reason\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\x03R\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAtB\x12\n" +
	"\x10_counterparty_idB\t\n" +
	"\a_reason\"\x9d\x02\n" +
	"\tInventory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\x03R\vwarehouseId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\x03R\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12&\n" +
	"\fcompleted_at\x18\a \x01(\tH\x00R\vcompletedAt\x88\x01\x01\x121\n" +
	"\x05items\x18\b \x03(\v2\x1b.warehouse.v1.InventoryItemR\x05itemsB\x0f\n" +
	"\r_completed_at\"\xeb\x01\n" +
	"\rInventoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\finventory_id\x18\x02 \x01(\x03R\vinventoryId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12!\n" +
	"\fexpected_qty\x18\x04 \x01(\tR\vexpectedQty\x12\"\n" +
	"\n" +
	"actual_qty\x18\x05 \x01(\tH\x00R\tactualQty\x88\x01\x01\x12#\n" +
	"\n" +
	"difference\x18\x06 \x01(\tH\x01R\n" +
	"difference\x88\x01\x01B\r\n" +
	"\v_actual_qtyB\r\n" +
	"\v_differenceBIZGgithub.com/makesalekz/warehouse/api/warehouse/v1;warehouse_v1b\x06proto3"

var (
	file_api_warehouse_v1_models_proto_rawDescOnce sync.Once
	file_api_warehouse_v1_models_proto_rawDescData []byte
)

func file_api_warehouse_v1_models_proto_rawDescGZIP() []byte {
	file_api_warehouse_v1_models_proto_rawDescOnce.Do(func() {
		file_api_warehouse_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_warehouse_v1_models_proto_rawDesc), len(file_api_warehouse_v1_models_proto_rawDesc)))
	})
	return file_api_warehouse_v1_models_proto_rawDescData
}

var file_api_warehouse_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_warehouse_v1_models_proto_goTypes = []any{
	(*Warehouse)(nil),     // 0: warehouse.v1.Warehouse
	(*StockItem)(nil),     // 1: warehouse.v1.StockItem
	(*StockMovement)(nil), // 2: warehouse.v1.StockMovement
	(*Inventory)(nil),     // 3: warehouse.v1.Inventory
	(*InventoryItem)(nil), // 4: warehouse.v1.InventoryItem
}
var file_api_warehouse_v1_models_proto_depIdxs = []int32{
	4, // 0: warehouse.v1.Inventory.items:type_name -> warehouse.v1.InventoryItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_warehouse_v1_models_proto_init() }
func file_api_warehouse_v1_models_proto_init() {
	if File_api_warehouse_v1_models_proto != nil {
		return
	}
	file_api_warehouse_v1_models_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_warehouse_v1_models_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_warehouse_v1_models_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_warehouse_v1_models_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_warehouse_v1_models_proto_rawDesc), len(file_api_warehouse_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_warehouse_v1_models_proto_goTypes,
		DependencyIndexes: file_api_warehouse_v1_models_proto_depIdxs,
		MessageInfos:      file_api_warehouse_v1_models_proto_msgTypes,
	}.Build()
	File_api_warehouse_v1_models_proto = out.File
	file_api_warehouse_v1_models_proto_goTypes = nil
	file_api_warehouse_v1_models_proto_depIdxs = nil
}
