// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/warehouse/v1/warehouse.proto

package warehouse_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WarehouseService_CreateWarehouse_FullMethodName   = "/warehouse.v1.WarehouseService/CreateWarehouse"
	WarehouseService_GetWarehouse_FullMethodName      = "/warehouse.v1.WarehouseService/GetWarehouse"
	WarehouseService_ListWarehouses_FullMethodName    = "/warehouse.v1.WarehouseService/ListWarehouses"
	WarehouseService_UpdateWarehouse_FullMethodName   = "/warehouse.v1.WarehouseService/UpdateWarehouse"
	WarehouseService_DeleteWarehouse_FullMethodName   = "/warehouse.v1.WarehouseService/DeleteWarehouse"
	WarehouseService_GetStockItems_FullMethodName     = "/warehouse.v1.WarehouseService/GetStockItems"
	WarehouseService_GetStockByProduct_FullMethodName = "/warehouse.v1.WarehouseService/GetStockByProduct"
	WarehouseService_CreateReceipt_FullMethodName     = "/warehouse.v1.WarehouseService/CreateReceipt"
	WarehouseService_CreateTransfer_FullMethodName    = "/warehouse.v1.WarehouseService/CreateTransfer"
	WarehouseService_CreateWriteOff_FullMethodName    = "/warehouse.v1.WarehouseService/CreateWriteOff"
	WarehouseService_CreateGift_FullMethodName        = "/warehouse.v1.WarehouseService/CreateGift"
	WarehouseService_ListMovements_FullMethodName     = "/warehouse.v1.WarehouseService/ListMovements"
	WarehouseService_SetMinQuantity_FullMethodName    = "/warehouse.v1.WarehouseService/SetMinQuantity"
	WarehouseService_GetLowStockItems_FullMethodName  = "/warehouse.v1.WarehouseService/GetLowStockItems"
	WarehouseService_StartInventory_FullMethodName    = "/warehouse.v1.WarehouseService/StartInventory"
	WarehouseService_SetInventoryItem_FullMethodName  = "/warehouse.v1.WarehouseService/SetInventoryItem"
	WarehouseService_CompleteInventory_FullMethodName = "/warehouse.v1.WarehouseService/CompleteInventory"
	WarehouseService_GetInventory_FullMethodName      = "/warehouse.v1.WarehouseService/GetInventory"
)

// WarehouseServiceClient is the client API for WarehouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarehouseServiceClient interface {
	CreateWarehouse(ctx context.Context, in *CreateWarehouseRequest, opts ...grpc.CallOption) (*CreateWarehouseReply, error)
	GetWarehouse(ctx context.Context, in *GetWarehouseRequest, opts ...grpc.CallOption) (*GetWarehouseReply, error)
	ListWarehouses(ctx context.Context, in *ListWarehousesRequest, opts ...grpc.CallOption) (*ListWarehousesReply, error)
	UpdateWarehouse(ctx context.Context, in *UpdateWarehouseRequest, opts ...grpc.CallOption) (*UpdateWarehouseReply, error)
	DeleteWarehouse(ctx context.Context, in *DeleteWarehouseRequest, opts ...grpc.CallOption) (*DeleteWarehouseReply, error)
	GetStockItems(ctx context.Context, in *GetStockItemsRequest, opts ...grpc.CallOption) (*GetStockItemsReply, error)
	GetStockByProduct(ctx context.Context, in *GetStockByProductRequest, opts ...grpc.CallOption) (*GetStockByProductReply, error)
	CreateReceipt(ctx context.Context, in *CreateReceiptRequest, opts ...grpc.CallOption) (*CreateReceiptReply, error)
	CreateTransfer(ctx context.Context, in *CreateTransferRequest, opts ...grpc.CallOption) (*CreateTransferReply, error)
	CreateWriteOff(ctx context.Context, in *CreateWriteOffRequest, opts ...grpc.CallOption) (*CreateWriteOffReply, error)
	CreateGift(ctx context.Context, in *CreateGiftRequest, opts ...grpc.CallOption) (*CreateGiftReply, error)
	ListMovements(ctx context.Context, in *ListMovementsRequest, opts ...grpc.CallOption) (*ListMovementsReply, error)
	SetMinQuantity(ctx context.Context, in *SetMinQuantityRequest, opts ...grpc.CallOption) (*SetMinQuantityReply, error)
	GetLowStockItems(ctx context.Context, in *GetLowStockItemsRequest, opts ...grpc.CallOption) (*GetLowStockItemsReply, error)
	StartInventory(ctx context.Context, in *StartInventoryRequest, opts ...grpc.CallOption) (*StartInventoryReply, error)
	SetInventoryItem(ctx context.Context, in *SetInventoryItemRequest, opts ...grpc.CallOption) (*SetInventoryItemReply, error)
	CompleteInventory(ctx context.Context, in *CompleteInventoryRequest, opts ...grpc.CallOption) (*CompleteInventoryReply, error)
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryReply, error)
}

type warehouseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWarehouseServiceClient(cc grpc.ClientConnInterface) WarehouseServiceClient {
	return &warehouseServiceClient{cc}
}

func (c *warehouseServiceClient) CreateWarehouse(ctx context.Context, in *CreateWarehouseRequest, opts ...grpc.CallOption) (*CreateWarehouseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWarehouseReply)
	err := c.cc.Invoke(ctx, WarehouseService_CreateWarehouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) GetWarehouse(ctx context.Context, in *GetWarehouseRequest, opts ...grpc.CallOption) (*GetWarehouseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWarehouseReply)
	err := c.cc.Invoke(ctx, WarehouseService_GetWarehouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) ListWarehouses(ctx context.Context, in *ListWarehousesRequest, opts ...grpc.CallOption) (*ListWarehousesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWarehousesReply)
	err := c.cc.Invoke(ctx, WarehouseService_ListWarehouses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) UpdateWarehouse(ctx context.Context, in *UpdateWarehouseRequest, opts ...grpc.CallOption) (*UpdateWarehouseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWarehouseReply)
	err := c.cc.Invoke(ctx, WarehouseService_UpdateWarehouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) DeleteWarehouse(ctx context.Context, in *DeleteWarehouseRequest, opts ...grpc.CallOption) (*DeleteWarehouseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWarehouseReply)
	err := c.cc.Invoke(ctx, WarehouseService_DeleteWarehouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) GetStockItems(ctx context.Context, in *GetStockItemsRequest, opts ...grpc.CallOption) (*GetStockItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockItemsReply)
	err := c.cc.Invoke(ctx, WarehouseService_GetStockItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) GetStockByProduct(ctx context.Context, in *GetStockByProductRequest, opts ...grpc.CallOption) (*GetStockByProductReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockByProductReply)
	err := c.cc.Invoke(ctx, WarehouseService_GetStockByProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreateReceipt(ctx context.Context, in *CreateReceiptRequest, opts ...grpc.CallOption) (*CreateReceiptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReceiptReply)
	err := c.cc.Invoke(ctx, WarehouseService_CreateReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreateTransfer(ctx context.Context, in *CreateTransferRequest, opts ...grpc.CallOption) (*CreateTransferReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTransferReply)
	err := c.cc.Invoke(ctx, WarehouseService_CreateTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreateWriteOff(ctx context.Context, in *CreateWriteOffRequest, opts ...grpc.CallOption) (*CreateWriteOffReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWriteOffReply)
	err := c.cc.Invoke(ctx, WarehouseService_CreateWriteOff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreateGift(ctx context.Context, in *CreateGiftRequest, opts ...grpc.CallOption) (*CreateGiftReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGiftReply)
	err := c.cc.Invoke(ctx, WarehouseService_CreateGift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) ListMovements(ctx context.Context, in *ListMovementsRequest, opts ...grpc.CallOption) (*ListMovementsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMovementsReply)
	err := c.cc.Invoke(ctx, WarehouseService_ListMovements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) SetMinQuantity(ctx context.Context, in *SetMinQuantityRequest, opts ...grpc.CallOption) (*SetMinQuantityReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMinQuantityReply)
	err := c.cc.Invoke(ctx, WarehouseService_SetMinQuantity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) GetLowStockItems(ctx context.Context, in *GetLowStockItemsRequest, opts ...grpc.CallOption) (*GetLowStockItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLowStockItemsReply)
	err := c.cc.Invoke(ctx, WarehouseService_GetLowStockItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) StartInventory(ctx context.Context, in *StartInventoryRequest, opts ...grpc.CallOption) (*StartInventoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInventoryReply)
	err := c.cc.Invoke(ctx, WarehouseService_StartInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) SetInventoryItem(ctx context.Context, in *SetInventoryItemRequest, opts ...grpc.CallOption) (*SetInventoryItemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInventoryItemReply)
	err := c.cc.Invoke(ctx, WarehouseService_SetInventoryItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CompleteInventory(ctx context.Context, in *CompleteInventoryRequest, opts ...grpc.CallOption) (*CompleteInventoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteInventoryReply)
	err := c.cc.Invoke(ctx, WarehouseService_CompleteInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryReply)
	err := c.cc.Invoke(ctx, WarehouseService_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarehouseServiceServer is the server API for WarehouseService service.
// All implementations must embed UnimplementedWarehouseServiceServer
// for forward compatibility.
type WarehouseServiceServer interface {
	CreateWarehouse(context.Context, *CreateWarehouseRequest) (*CreateWarehouseReply, error)
	GetWarehouse(context.Context, *GetWarehouseRequest) (*GetWarehouseReply, error)
	ListWarehouses(context.Context, *ListWarehousesRequest) (*ListWarehousesReply, error)
	UpdateWarehouse(context.Context, *UpdateWarehouseRequest) (*UpdateWarehouseReply, error)
	DeleteWarehouse(context.Context, *DeleteWarehouseRequest) (*DeleteWarehouseReply, error)
	GetStockItems(context.Context, *GetStockItemsRequest) (*GetStockItemsReply, error)
	GetStockByProduct(context.Context, *GetStockByProductRequest) (*GetStockByProductReply, error)
	CreateReceipt(context.Context, *CreateReceiptRequest) (*CreateReceiptReply, error)
	CreateTransfer(context.Context, *CreateTransferRequest) (*CreateTransferReply, error)
	CreateWriteOff(context.Context, *CreateWriteOffRequest) (*CreateWriteOffReply, error)
	CreateGift(context.Context, *CreateGiftRequest) (*CreateGiftReply, error)
	ListMovements(context.Context, *ListMovementsRequest) (*ListMovementsReply, error)
	SetMinQuantity(context.Context, *SetMinQuantityRequest) (*SetMinQuantityReply, error)
	GetLowStockItems(context.Context, *GetLowStockItemsRequest) (*GetLowStockItemsReply, error)
	StartInventory(context.Context, *StartInventoryRequest) (*StartInventoryReply, error)
	SetInventoryItem(context.Context, *SetInventoryItemRequest) (*SetInventoryItemReply, error)
	CompleteInventory(context.Context, *CompleteInventoryRequest) (*CompleteInventoryReply, error)
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryReply, error)
	mustEmbedUnimplementedWarehouseServiceServer()
}

// UnimplementedWarehouseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWarehouseServiceServer struct{}

func (UnimplementedWarehouseServiceServer) CreateWarehouse(context.Context, *CreateWarehouseRequest) (*CreateWarehouseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWarehouse not implemented")
}
func (UnimplementedWarehouseServiceServer) GetWarehouse(context.Context, *GetWarehouseRequest) (*GetWarehouseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWarehouse not implemented")
}
func (UnimplementedWarehouseServiceServer) ListWarehouses(context.Context, *ListWarehousesRequest) (*ListWarehousesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWarehouses not implemented")
}
func (UnimplementedWarehouseServiceServer) UpdateWarehouse(context.Context, *UpdateWarehouseRequest) (*UpdateWarehouseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWarehouse not implemented")
}
func (UnimplementedWarehouseServiceServer) DeleteWarehouse(context.Context, *DeleteWarehouseRequest) (*DeleteWarehouseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWarehouse not implemented")
}
func (UnimplementedWarehouseServiceServer) GetStockItems(context.Context, *GetStockItemsRequest) (*GetStockItemsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockItems not implemented")
}
func (UnimplementedWarehouseServiceServer) GetStockByProduct(context.Context, *GetStockByProductRequest) (*GetStockByProductReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockByProduct not implemented")
}
func (UnimplementedWarehouseServiceServer) CreateReceipt(context.Context, *CreateReceiptRequest) (*CreateReceiptReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReceipt not implemented")
}
func (UnimplementedWarehouseServiceServer) CreateTransfer(context.Context, *CreateTransferRequest) (*CreateTransferReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTransfer not implemented")
}
func (UnimplementedWarehouseServiceServer) CreateWriteOff(context.Context, *CreateWriteOffRequest) (*CreateWriteOffReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWriteOff not implemented")
}
func (UnimplementedWarehouseServiceServer) CreateGift(context.Context, *CreateGiftRequest) (*CreateGiftReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGift not implemented")
}
func (UnimplementedWarehouseServiceServer) ListMovements(context.Context, *ListMovementsRequest) (*ListMovementsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMovements not implemented")
}
func (UnimplementedWarehouseServiceServer) SetMinQuantity(context.Context, *SetMinQuantityRequest) (*SetMinQuantityReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMinQuantity not implemented")
}
func (UnimplementedWarehouseServiceServer) GetLowStockItems(context.Context, *GetLowStockItemsRequest) (*GetLowStockItemsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLowStockItems not implemented")
}
func (UnimplementedWarehouseServiceServer) StartInventory(context.Context, *StartInventoryRequest) (*StartInventoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInventory not implemented")
}
func (UnimplementedWarehouseServiceServer) SetInventoryItem(context.Context, *SetInventoryItemRequest) (*SetInventoryItemReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInventoryItem not implemented")
}
func (UnimplementedWarehouseServiceServer) CompleteInventory(context.Context, *CompleteInventoryRequest) (*CompleteInventoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteInventory not implemented")
}
func (UnimplementedWarehouseServiceServer) GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedWarehouseServiceServer) mustEmbedUnimplementedWarehouseServiceServer() {}
func (UnimplementedWarehouseServiceServer) testEmbeddedByValue()                          {}

// UnsafeWarehouseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarehouseServiceServer will
// result in compilation errors.
type UnsafeWarehouseServiceServer interface {
	mustEmbedUnimplementedWarehouseServiceServer()
}

func RegisterWarehouseServiceServer(s grpc.ServiceRegistrar, srv WarehouseServiceServer) {
	// If the following call panics, it indicates UnimplementedWarehouseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WarehouseService_ServiceDesc, srv)
}

func _WarehouseService_CreateWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWarehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateWarehouse(ctx, req.(*CreateWarehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_GetWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWarehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).GetWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_GetWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).GetWarehouse(ctx, req.(*GetWarehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_ListWarehouses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWarehousesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).ListWarehouses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_ListWarehouses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).ListWarehouses(ctx, req.(*ListWarehousesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_UpdateWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWarehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).UpdateWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_UpdateWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).UpdateWarehouse(ctx, req.(*UpdateWarehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_DeleteWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWarehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).DeleteWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_DeleteWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).DeleteWarehouse(ctx, req.(*DeleteWarehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_GetStockItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).GetStockItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_GetStockItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).GetStockItems(ctx, req.(*GetStockItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_GetStockByProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockByProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).GetStockByProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_GetStockByProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).GetStockByProduct(ctx, req.(*GetStockByProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreateReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateReceipt(ctx, req.(*CreateReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateTransfer(ctx, req.(*CreateTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreateWriteOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWriteOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateWriteOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateWriteOff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateWriteOff(ctx, req.(*CreateWriteOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreateGift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateGift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateGift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateGift(ctx, req.(*CreateGiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_ListMovements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMovementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).ListMovements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_ListMovements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).ListMovements(ctx, req.(*ListMovementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_SetMinQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMinQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).SetMinQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_SetMinQuantity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).SetMinQuantity(ctx, req.(*SetMinQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_GetLowStockItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLowStockItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).GetLowStockItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_GetLowStockItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).GetLowStockItems(ctx, req.(*GetLowStockItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_StartInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).StartInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_StartInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).StartInventory(ctx, req.(*StartInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_SetInventoryItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInventoryItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).SetInventoryItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_SetInventoryItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).SetInventoryItem(ctx, req.(*SetInventoryItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CompleteInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CompleteInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CompleteInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CompleteInventory(ctx, req.(*CompleteInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WarehouseService_ServiceDesc is the grpc.ServiceDesc for WarehouseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarehouseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warehouse.v1.WarehouseService",
	HandlerType: (*WarehouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWarehouse",
			Handler:    _WarehouseService_CreateWarehouse_Handler,
		},
		{
			MethodName: "GetWarehouse",
			Handler:    _WarehouseService_GetWarehouse_Handler,
		},
		{
			MethodName: "ListWarehouses",
			Handler:    _WarehouseService_ListWarehouses_Handler,
		},
		{
			MethodName: "UpdateWarehouse",
			Handler:    _WarehouseService_UpdateWarehouse_Handler,
		},
		{
			MethodName: "DeleteWarehouse",
			Handler:    _WarehouseService_DeleteWarehouse_Handler,
		},
		{
			MethodName: "GetStockItems",
			Handler:    _WarehouseService_GetStockItems_Handler,
		},
		{
			MethodName: "GetStockByProduct",
			Handler:    _WarehouseService_GetStockByProduct_Handler,
		},
		{
			MethodName: "CreateReceipt",
			Handler:    _WarehouseService_CreateReceipt_Handler,
		},
		{
			MethodName: "CreateTransfer",
			Handler:    _WarehouseService_CreateTransfer_Handler,
		},
		{
			MethodName: "CreateWriteOff",
			Handler:    _WarehouseService_CreateWriteOff_Handler,
		},
		{
			MethodName: "CreateGift",
			Handler:    _WarehouseService_CreateGift_Handler,
		},
		{
			MethodName: "ListMovements",
			Handler:    _WarehouseService_ListMovements_Handler,
		},
		{
			MethodName: "SetMinQuantity",
			Handler:    _WarehouseService_SetMinQuantity_Handler,
		},
		{
			MethodName: "GetLowStockItems",
			Handler:    _WarehouseService_GetLowStockItems_Handler,
		},
		{
			MethodName: "StartInventory",
			Handler:    _WarehouseService_StartInventory_Handler,
		},
		{
			MethodName: "SetInventoryItem",
			Handler:    _WarehouseService_SetInventoryItem_Handler,
		},
		{
			MethodName: "CompleteInventory",
			Handler:    _WarehouseService_CompleteInventory_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _WarehouseService_GetInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/warehouse/v1/warehouse.proto",
}
