// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/warehouse/v1/warehouse.proto

package warehouse_v1

import (
	v1 "github.com/makesalekz/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	StoreId       *int64                 `protobuf:"varint,5,opt,name=store_id,json=storeId,proto3,oneof" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseRequest) Reset() {
	*x = CreateWarehouseRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseRequest) ProtoMessage() {}

func (x *CreateWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseRequest.ProtoReflect.Descriptor instead.
func (*CreateWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWarehouseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWarehouseRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateWarehouseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWarehouseRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateWarehouseRequest) GetStoreId() int64 {
	if x != nil && x.StoreId != nil {
		return *x.StoreId
	}
	return 0
}

type CreateWarehouseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouse     *Warehouse             `protobuf:"bytes,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseReply) Reset() {
	*x = CreateWarehouseReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseReply) ProtoMessage() {}

func (x *CreateWarehouseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseReply.ProtoReflect.Descriptor instead.
func (*CreateWarehouseReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWarehouseReply) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

type GetWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehouseRequest) Reset() {
	*x = GetWarehouseRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehouseRequest) ProtoMessage() {}

func (x *GetWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehouseRequest.ProtoReflect.Descriptor instead.
func (*GetWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *GetWarehouseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWarehouseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouse     *Warehouse             `protobuf:"bytes,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehouseReply) Reset() {
	*x = GetWarehouseReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehouseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehouseReply) ProtoMessage() {}

func (x *GetWarehouseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehouseReply.ProtoReflect.Descriptor instead.
func (*GetWarehouseReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{3}
}

func (x *GetWarehouseReply) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

type ListWarehousesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	StoreId       *int64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3,oneof" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesRequest) Reset() {
	*x = ListWarehousesRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesRequest) ProtoMessage() {}

func (x *ListWarehousesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesRequest.ProtoReflect.Descriptor instead.
func (*ListWarehousesRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{4}
}

func (x *ListWarehousesRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *ListWarehousesRequest) GetStoreId() int64 {
	if x != nil && x.StoreId != nil {
		return *x.StoreId
	}
	return 0
}

type ListWarehousesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Warehouse           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesReply) Reset() {
	*x = ListWarehousesReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesReply) ProtoMessage() {}

func (x *ListWarehousesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesReply.ProtoReflect.Descriptor instead.
func (*ListWarehousesReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{5}
}

func (x *ListWarehousesReply) GetItems() []*Warehouse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListWarehousesReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type UpdateWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	StoreId       *int64                 `protobuf:"varint,7,opt,name=store_id,json=storeId,proto3,oneof" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarehouseRequest) Reset() {
	*x = UpdateWarehouseRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarehouseRequest) ProtoMessage() {}

func (x *UpdateWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarehouseRequest.ProtoReflect.Descriptor instead.
func (*UpdateWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWarehouseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWarehouseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateWarehouseRequest) GetStoreId() int64 {
	if x != nil && x.StoreId != nil {
		return *x.StoreId
	}
	return 0
}

type UpdateWarehouseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouse     *Warehouse             `protobuf:"bytes,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarehouseReply) Reset() {
	*x = UpdateWarehouseReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarehouseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarehouseReply) ProtoMessage() {}

func (x *UpdateWarehouseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarehouseReply.ProtoReflect.Descriptor instead.
func (*UpdateWarehouseReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateWarehouseReply) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

type DeleteWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWarehouseRequest) Reset() {
	*x = DeleteWarehouseRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWarehouseRequest) ProtoMessage() {}

func (x *DeleteWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWarehouseRequest.ProtoReflect.Descriptor instead.
func (*DeleteWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteWarehouseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWarehouseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWarehouseReply) Reset() {
	*x = DeleteWarehouseReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWarehouseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWarehouseReply) ProtoMessage() {}

func (x *DeleteWarehouseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWarehouseReply.ProtoReflect.Descriptor instead.
func (*DeleteWarehouseReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{9}
}

type GetStockItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int64                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockItemsRequest) Reset() {
	*x = GetStockItemsRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockItemsRequest) ProtoMessage() {}

func (x *GetStockItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockItemsRequest.ProtoReflect.Descriptor instead.
func (*GetStockItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{10}
}

func (x *GetStockItemsRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *GetStockItemsRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type GetStockItemsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockItemsReply) Reset() {
	*x = GetStockItemsReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockItemsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockItemsReply) ProtoMessage() {}

func (x *GetStockItemsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockItemsReply.ProtoReflect.Descriptor instead.
func (*GetStockItemsReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{11}
}

func (x *GetStockItemsReply) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetStockItemsReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type GetStockByProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockByProductRequest) Reset() {
	*x = GetStockByProductRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockByProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockByProductRequest) ProtoMessage() {}

func (x *GetStockByProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockByProductRequest.ProtoReflect.Descriptor instead.
func (*GetStockByProductRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{12}
}

func (x *GetStockByProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetStockByProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockByProductReply) Reset() {
	*x = GetStockByProductReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockByProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockByProductReply) ProtoMessage() {}

func (x *GetStockByProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockByProductReply.ProtoReflect.Descriptor instead.
func (*GetStockByProductReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{13}
}

func (x *GetStockByProductReply) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReceiptItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptItem) Reset() {
	*x = ReceiptItem{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptItem) ProtoMessage() {}

func (x *ReceiptItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptItem.ProtoReflect.Descriptor instead.
func (*ReceiptItem) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{14}
}

func (x *ReceiptItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReceiptItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type CreateReceiptRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId    int64                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Items          []*ReceiptItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	CounterpartyId *int64                 `protobuf:"varint,3,opt,name=counterparty_id,json=counterpartyId,proto3,oneof" json:"counterparty_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateReceiptRequest) Reset() {
	*x = CreateReceiptRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiptRequest) ProtoMessage() {}

func (x *CreateReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiptRequest.ProtoReflect.Descriptor instead.
func (*CreateReceiptRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{15}
}

func (x *CreateReceiptRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *CreateReceiptRequest) GetItems() []*ReceiptItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateReceiptRequest) GetCounterpartyId() int64 {
	if x != nil && x.CounterpartyId != nil {
		return *x.CounterpartyId
	}
	return 0
}

type CreateReceiptReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movements     []*StockMovement       `protobuf:"bytes,1,rep,name=movements,proto3" json:"movements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceiptReply) Reset() {
	*x = CreateReceiptReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceiptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiptReply) ProtoMessage() {}

func (x *CreateReceiptReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiptReply.ProtoReflect.Descriptor instead.
func (*CreateReceiptReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{16}
}

func (x *CreateReceiptReply) GetMovements() []*StockMovement {
	if x != nil {
		return x.Movements
	}
	return nil
}

type TransferItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferItem) Reset() {
	*x = TransferItem{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferItem) ProtoMessage() {}

func (x *TransferItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferItem.ProtoReflect.Descriptor instead.
func (*TransferItem) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{17}
}

func (x *TransferItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *TransferItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type CreateTransferRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SourceWarehouseId int64                  `protobuf:"varint,1,opt,name=source_warehouse_id,json=sourceWarehouseId,proto3" json:"source_warehouse_id,omitempty"`
	TargetWarehouseId int64                  `protobuf:"varint,2,opt,name=target_warehouse_id,json=targetWarehouseId,proto3" json:"target_warehouse_id,omitempty"`
	Items             []*TransferItem        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{18}
}

func (x *CreateTransferRequest) GetSourceWarehouseId() int64 {
	if x != nil {
		return x.SourceWarehouseId
	}
	return 0
}

func (x *CreateTransferRequest) GetTargetWarehouseId() int64 {
	if x != nil {
		return x.TargetWarehouseId
	}
	return 0
}

func (x *CreateTransferRequest) GetItems() []*TransferItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateTransferReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movements     []*StockMovement       `protobuf:"bytes,1,rep,name=movements,proto3" json:"movements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferReply) Reset() {
	*x = CreateTransferReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferReply) ProtoMessage() {}

func (x *CreateTransferReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferReply.ProtoReflect.Descriptor instead.
func (*CreateTransferReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{19}
}

func (x *CreateTransferReply) GetMovements() []*StockMovement {
	if x != nil {
		return x.Movements
	}
	return nil
}

type WriteOffItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOffItem) Reset() {
	*x = WriteOffItem{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOffItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOffItem) ProtoMessage() {}

func (x *WriteOffItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOffItem.ProtoReflect.Descriptor instead.
func (*WriteOffItem) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{20}
}

func (x *WriteOffItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *WriteOffItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *WriteOffItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateWriteOffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int64                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Items         []*WriteOffItem        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWriteOffRequest) Reset() {
	*x = CreateWriteOffRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWriteOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWriteOffRequest) ProtoMessage() {}

func (x *CreateWriteOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWriteOffRequest.ProtoReflect.Descriptor instead.
func (*CreateWriteOffRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{21}
}

func (x *CreateWriteOffRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *CreateWriteOffRequest) GetItems() []*WriteOffItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateWriteOffReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movements     []*StockMovement       `protobuf:"bytes,1,rep,name=movements,proto3" json:"movements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWriteOffReply) Reset() {
	*x = CreateWriteOffReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWriteOffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWriteOffReply) ProtoMessage() {}

func (x *CreateWriteOffReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWriteOffReply.ProtoReflect.Descriptor instead.
func (*CreateWriteOffReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{22}
}

func (x *CreateWriteOffReply) GetMovements() []*StockMovement {
	if x != nil {
		return x.Movements
	}
	return nil
}

type GiftItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiftItem) Reset() {
	*x = GiftItem{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiftItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftItem) ProtoMessage() {}

func (x *GiftItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftItem.ProtoReflect.Descriptor instead.
func (*GiftItem) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{23}
}

func (x *GiftItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GiftItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type CreateGiftRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId    int64                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Items          []*GiftItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	CounterpartyId int64                  `protobuf:"varint,3,opt,name=counterparty_id,json=counterpartyId,proto3" json:"counterparty_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateGiftRequest) Reset() {
	*x = CreateGiftRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGiftRequest) ProtoMessage() {}

func (x *CreateGiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGiftRequest.ProtoReflect.Descriptor instead.
func (*CreateGiftRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{24}
}

func (x *CreateGiftRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *CreateGiftRequest) GetItems() []*GiftItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateGiftRequest) GetCounterpartyId() int64 {
	if x != nil {
		return x.CounterpartyId
	}
	return 0
}

type CreateGiftReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movements     []*StockMovement       `protobuf:"bytes,1,rep,name=movements,proto3" json:"movements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGiftReply) Reset() {
	*x = CreateGiftReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGiftReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGiftReply) ProtoMessage() {}

func (x *CreateGiftReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGiftReply.ProtoReflect.Descriptor instead.
func (*CreateGiftReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{25}
}

func (x *CreateGiftReply) GetMovements() []*StockMovement {
	if x != nil {
		return x.Movements
	}
	return nil
}

type ListMovementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int64                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,3,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMovementsRequest) Reset() {
	*x = ListMovementsRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMovementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMovementsRequest) ProtoMessage() {}

func (x *ListMovementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMovementsRequest.ProtoReflect.Descriptor instead.
func (*ListMovementsRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{26}
}

func (x *ListMovementsRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *ListMovementsRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ListMovementsRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type ListMovementsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockMovement       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMovementsReply) Reset() {
	*x = ListMovementsReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMovementsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMovementsReply) ProtoMessage() {}

func (x *ListMovementsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMovementsReply.ProtoReflect.Descriptor instead.
func (*ListMovementsReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{27}
}

func (x *ListMovementsReply) GetItems() []*StockMovement {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMovementsReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type StartInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int64                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInventoryRequest) Reset() {
	*x = StartInventoryRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInventoryRequest) ProtoMessage() {}

func (x *StartInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInventoryRequest.ProtoReflect.Descriptor instead.
func (*StartInventoryRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{28}
}

func (x *StartInventoryRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

type StartInventoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInventoryReply) Reset() {
	*x = StartInventoryReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInventoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInventoryReply) ProtoMessage() {}

func (x *StartInventoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInventoryReply.ProtoReflect.Descriptor instead.
func (*StartInventoryReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{29}
}

func (x *StartInventoryReply) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type SetInventoryItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   int64                  `protobuf:"varint,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ActualQty     string                 `protobuf:"bytes,3,opt,name=actual_qty,json=actualQty,proto3" json:"actual_qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInventoryItemRequest) Reset() {
	*x = SetInventoryItemRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInventoryItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInventoryItemRequest) ProtoMessage() {}

func (x *SetInventoryItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInventoryItemRequest.ProtoReflect.Descriptor instead.
func (*SetInventoryItemRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{30}
}

func (x *SetInventoryItemRequest) GetInventoryId() int64 {
	if x != nil {
		return x.InventoryId
	}
	return 0
}

func (x *SetInventoryItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SetInventoryItemRequest) GetActualQty() string {
	if x != nil {
		return x.ActualQty
	}
	return ""
}

type SetInventoryItemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInventoryItemReply) Reset() {
	*x = SetInventoryItemReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInventoryItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInventoryItemReply) ProtoMessage() {}

func (x *SetInventoryItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInventoryItemReply.ProtoReflect.Descriptor instead.
func (*SetInventoryItemReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{31}
}

func (x *SetInventoryItemReply) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CompleteInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   int64                  `protobuf:"varint,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteInventoryRequest) Reset() {
	*x = CompleteInventoryRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteInventoryRequest) ProtoMessage() {}

func (x *CompleteInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteInventoryRequest.ProtoReflect.Descriptor instead.
func (*CompleteInventoryRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{32}
}

func (x *CompleteInventoryRequest) GetInventoryId() int64 {
	if x != nil {
		return x.InventoryId
	}
	return 0
}

type CompleteInventoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteInventoryReply) Reset() {
	*x = CompleteInventoryReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteInventoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteInventoryReply) ProtoMessage() {}

func (x *CompleteInventoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteInventoryReply.ProtoReflect.Descriptor instead.
func (*CompleteInventoryReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{33}
}

func (x *CompleteInventoryReply) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   int64                  `protobuf:"varint,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{34}
}

func (x *GetInventoryRequest) GetInventoryId() int64 {
	if x != nil {
		return x.InventoryId
	}
	return 0
}

type GetInventoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryReply) Reset() {
	*x = GetInventoryReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryReply) ProtoMessage() {}

func (x *GetInventoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryReply.ProtoReflect.Descriptor instead.
func (*GetInventoryReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{35}
}

func (x *GetInventoryReply) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type SetMinQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int64                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	MinQuantity   string                 `protobuf:"bytes,3,opt,name=min_quantity,json=minQuantity,proto3" json:"min_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMinQuantityRequest) Reset() {
	*x = SetMinQuantityRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMinQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMinQuantityRequest) ProtoMessage() {}

func (x *SetMinQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMinQuantityRequest.ProtoReflect.Descriptor instead.
func (*SetMinQuantityRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{36}
}

func (x *SetMinQuantityRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *SetMinQuantityRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SetMinQuantityRequest) GetMinQuantity() string {
	if x != nil {
		return x.MinQuantity
	}
	return ""
}

type SetMinQuantityReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *StockItem             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMinQuantityReply) Reset() {
	*x = SetMinQuantityReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMinQuantityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMinQuantityReply) ProtoMessage() {}

func (x *SetMinQuantityReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMinQuantityReply.ProtoReflect.Descriptor instead.
func (*SetMinQuantityReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{37}
}

func (x *SetMinQuantityReply) GetItem() *StockItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetLowStockItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int64                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLowStockItemsRequest) Reset() {
	*x = GetLowStockItemsRequest{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLowStockItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLowStockItemsRequest) ProtoMessage() {}

func (x *GetLowStockItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLowStockItemsRequest.ProtoReflect.Descriptor instead.
func (*GetLowStockItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{38}
}

func (x *GetLowStockItemsRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

type GetLowStockItemsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLowStockItemsReply) Reset() {
	*x = GetLowStockItemsReply{}
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLowStockItemsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLowStockItemsReply) ProtoMessage() {}

func (x *GetLowStockItemsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_v1_warehouse_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLowStockItemsReply.ProtoReflect.Descriptor instead.
func (*GetLowStockItemsReply) Descriptor() ([]byte, []int) {
	return file_api_warehouse_v1_warehouse_proto_rawDescGZIP(), []int{39}
}

func (x *GetLowStockItemsReply) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_warehouse_v1_warehouse_proto protoreflect.FileDescriptor

const file_api_warehouse_v1_warehouse_proto_rawDesc = "" +
	"\n" +
	" api/warehouse/v1/warehouse.proto\x12\fwarehouse.v1\x1a\x1dapi/warehouse/v1/models.proto\x1a\x19api/utils/v1/models.proto\"\xa9\x01\n" +
	"\x16CreateWarehouseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1e\n" +
	"\bstore_id\x18\x05 \x01(\x03H\x00R\astoreId\x88\x01\x01B\v\n" +
	"\t_store_id\"M\n" +
	"\x14CreateWarehouseReply\x125\n" +
	"\twarehouse\x18\x01 \x01(\v2\x17.warehouse.v1.WarehouseR\twarehouse\"%\n" +
	"\x13GetWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"J\n" +
	"\x11GetWarehouseReply\x125\n" +
	"\twarehouse\x18\x01 \x01(\v2\x17.warehouse.v1.WarehouseR\twarehouse\"{\n" +
	"\x15ListWarehousesRequest\x125\n" +
	"\bpaginate\x18\x01 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\x12\x1e\n" +
	"\bstore_id\x18\x02 \x01(\x03H\x00R\astoreId\x88\x01\x01B\v\n" +
	"\t_store_id\"y\n" +
	"\x13ListWarehousesReply\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.warehouse.v1.WarehouseR\x05items\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate\"\xd6\x01\n" +
	"\x16UpdateWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1e\n" +
	"\bstore_id\x18\a \x01(\x03H\x00R\astoreId\x88\x01\x01B\v\n" +
	"\t_store_id\"M\n" +
	"\x14UpdateWarehouseReply\x125\n" +
	"\twarehouse\x18\x01 \x01(\v2\x17.warehouse.v1.WarehouseR\twarehouse\"(\n" +
	"\x16DeleteWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x16\n" +
	"\x14DeleteWarehouseReply\"p\n" +
	"\x14GetStockItemsRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x03R\vwarehouseId\x125\n" +
	"\bpaginate\x18\x02 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\"x\n" +
	"\x12GetStockItemsReply\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.warehouse.v1.StockItemR\x05items\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate\"9\n" +
	"\x18GetStockByProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"G\n" +
	"\x16GetStockByProductReply\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.warehouse.v1.StockItemR\x05items\"H\n" +
	"\vReceiptItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"\xac\x01\n" +
	"\x14CreateReceiptRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x03R\vwarehouseId\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.warehouse.v1.ReceiptItemR\x05items\x12,\n" +
	"\x0fcounterparty_id\x18\x03 \x01(\x03H\x00R\x0ecounterpartyId\x88\x01\x01B\x12\n" +
	"\x10_counterparty_id\"O\n" +
	"\x12CreateReceiptReply\x129\n" +
	"\tmovements\x18\x01 \x03(\v2\x1b.warehouse.v1.StockMovementR\tmovements\"I\n" +
	"\fTransferItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"\xa9\x01\n" +
	"\x15CreateTransferRequest\x12.\n" +
	"\x13source_warehouse_id\x18\x01 \x01(\x03R\x11sourceWarehouseId\x12.\n" +
	"\x13target_warehouse_id\x18\x02 \x01(\x03R\x11targetWarehouseId\x120\n" +
	"\x05items\x18\x03 \x03(\v2\x1a.warehouse.v1.TransferItemR\x05items\"P\n" +
	"\x13CreateTransferReply\x129\n" +
	"\tmovements\x18\x01 \x03(\v2\x1b.warehouse.v1.StockMovementR\tmovements\"a\n" +
	"\fWriteOffItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"l\n" +
	"\x15CreateWriteOffRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x03R\vwarehouseId\x120\n" +
	"\x05items\x18\x02 \x03(\v2\x1a.warehouse.v1.WriteOffItemR\x05items\"P\n" +
	"\x13CreateWriteOffReply\x129\n" +
	"\tmovements\x18\x01 \x03(\v2\x1b.warehouse.v1.StockMovementR\tmovements\"E\n" +
	"\bGiftItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"\x8d\x01\n" +
	"\x11CreateGiftRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x03R\vwarehouseId\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.warehouse.v1.GiftItemR\x05items\x12'\n" +
	"\x0fcounterparty_id\x18\x03 \x01(\x03R\x0ecounterpartyId\"L\n" +
	"\x0fCreateGiftReply\x129\n" +
	"\tmovements\x18\x01 \x03(\v2\x1b.warehouse.v1.StockMovementR\tmovements\"\x92\x01\n" +
	"\x14ListMovementsRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x03R\vwarehouseId\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x00R\x04type\x88\x01\x01\x125\n" +
	"\bpaginate\x18\x03 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginateB\a\n" +
	"\x05_type\"|\n" +
	"\x12ListMovementsReply\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.warehouse.v1.StockMovementR\x05items\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate\":\n" +
	"\x15StartInventoryRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x03R\vwarehouseId\"L\n" +
	"\x13StartInventoryReply\x125\n" +
	"\tinventory\x18\x01 \x01(\v2\x17.warehouse.v1.InventoryR\tinventory\"z\n" +
	"\x17SetInventoryItemRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\x03R\vinventoryId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1d\n" +
	"\n" +
	"actual_qty\x18\x03 \x01(\tR\tactualQty\"H\n" +
	"\x15SetInventoryItemReply\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.warehouse.v1.InventoryItemR\x04item\"=\n" +
	"\x18CompleteInventoryRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\x03R\vinventoryId\"O\n" +
	"\x16CompleteInventoryReply\x125\n" +
	"\tinventory\x18\x01 \x01(\v2\x17.warehouse.v1.InventoryR\tinventory\"8\n" +
	"\x13GetInventoryRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\x03R\vinventoryId\"J\n" +
	"\x11GetInventoryReply\x125\n" +
	"\tinventory\x18\x01 \x01(\v2\x17.warehouse.v1.InventoryR\tinventory\"|\n" +
	"\x15SetMinQuantityRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x03R\vwarehouseId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12!\n" +
	"\fmin_quantity\x18\x03 \x01(\tR\vminQuantity\"B\n" +
	"\x13SetMinQuantityReply\x12+\n" +
	"\x04item\x18\x01 \x01(\v2\x17.warehouse.v1.StockItemR\x04item\"<\n" +
	"\x17GetLowStockItemsRequest\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x03R\vwarehouseId\"F\n" +
	"\x15GetLowStockItemsReply\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.warehouse.v1.StockItemR\x05items2\xec\f\n" +
	"\x10WarehouseService\x12[\n" +
	"\x0fCreateWarehouse\x12$.warehouse.v1.CreateWarehouseRequest\x1a\".warehouse.v1.CreateWarehouseReply\x12R\n" +
	"\fGetWarehouse\x12!.warehouse.v1.GetWarehouseRequest\x1a\x1f.warehouse.v1.GetWarehouseReply\x12X\n" +
	"\x0eListWarehouses\x12#.warehouse.v1.ListWarehousesRequest\x1a!.warehouse.v1.ListWarehousesReply\x12[\n" +
	"\x0fUpdateWarehouse\x12$.warehouse.v1.UpdateWarehouseRequest\x1a\".warehouse.v1.UpdateWarehouseReply\x12[\n" +
	"\x0fDeleteWarehouse\x12$.warehouse.v1.DeleteWarehouseRequest\x1a\".warehouse.v1.DeleteWarehouseReply\x12U\n" +
	"\rGetStockItems\x12\".warehouse.v1.GetStockItemsRequest\x1a .warehouse.v1.GetStockItemsReply\x12a\n" +
	"\x11GetStockByProduct\x12&.warehouse.v1.GetStockByProductRequest\x1a$.warehouse.v1.GetStockByProductReply\x12U\n" +
	"\rCreateReceipt\x12\".warehouse.v1.CreateReceiptRequest\x1a .warehouse.v1.CreateReceiptReply\x12X\n" +
	"\x0eCreateTransfer\x12#.warehouse.v1.CreateTransferRequest\x1a!.warehouse.v1.CreateTransferReply\x12X\n" +
	"\x0eCreateWriteOff\x12#.warehouse.v1.CreateWriteOffRequest\x1a!.warehouse.v1.CreateWriteOffReply\x12L\n" +
	"\n" +
	"CreateGift\x12\x1f.warehouse.v1.CreateGiftRequest\x1a\x1d.warehouse.v1.CreateGiftReply\x12U\n" +
	"\rListMovements\x12\".warehouse.v1.ListMovementsRequest\x1a .warehouse.v1.ListMovementsReply\x12X\n" +
	"\x0eSetMinQuantity\x12#.warehouse.v1.SetMinQuantityRequest\x1a!.warehouse.v1.SetMinQuantityReply\x12^\n" +
	"\x10GetLowStockItems\x12%.warehouse.v1.GetLowStockItemsRequest\x1a#.warehouse.v1.GetLowStockItemsReply\x12X\n" +
	"\x0eStartInventory\x12#.warehouse.v1.StartInventoryRequest\x1a!.warehouse.v1.StartInventoryReply\x12^\n" +
	"\x10SetInventoryItem\x12%.warehouse.v1.SetInventoryItemRequest\x1a#.warehouse.v1.SetInventoryItemReply\x12a\n" +
	"\x11CompleteInventory\x12&.warehouse.v1.CompleteInventoryRequest\x1a$.warehouse.v1.CompleteInventoryReply\x12R\n" +
	"\fGetInventory\x12!.warehouse.v1.GetInventoryRequest\x1a\x1f.warehouse.v1.GetInventoryReplyB?Z=github.com/makesalekz/warehouse/api/warehouse/v1;warehouse_v1b\x06proto3"

var (
	file_api_warehouse_v1_warehouse_proto_rawDescOnce sync.Once
	file_api_warehouse_v1_warehouse_proto_rawDescData []byte
)

func file_api_warehouse_v1_warehouse_proto_rawDescGZIP() []byte {
	file_api_warehouse_v1_warehouse_proto_rawDescOnce.Do(func() {
		file_api_warehouse_v1_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_warehouse_v1_warehouse_proto_rawDesc), len(file_api_warehouse_v1_warehouse_proto_rawDesc)))
	})
	return file_api_warehouse_v1_warehouse_proto_rawDescData
}

var file_api_warehouse_v1_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_api_warehouse_v1_warehouse_proto_goTypes = []any{
	(*CreateWarehouseRequest)(nil),   // 0: warehouse.v1.CreateWarehouseRequest
	(*CreateWarehouseReply)(nil),     // 1: warehouse.v1.CreateWarehouseReply
	(*GetWarehouseRequest)(nil),      // 2: warehouse.v1.GetWarehouseRequest
	(*GetWarehouseReply)(nil),        // 3: warehouse.v1.GetWarehouseReply
	(*ListWarehousesRequest)(nil),    // 4: warehouse.v1.ListWarehousesRequest
	(*ListWarehousesReply)(nil),      // 5: warehouse.v1.ListWarehousesReply
	(*UpdateWarehouseRequest)(nil),   // 6: warehouse.v1.UpdateWarehouseRequest
	(*UpdateWarehouseReply)(nil),     // 7: warehouse.v1.UpdateWarehouseReply
	(*DeleteWarehouseRequest)(nil),   // 8: warehouse.v1.DeleteWarehouseRequest
	(*DeleteWarehouseReply)(nil),     // 9: warehouse.v1.DeleteWarehouseReply
	(*GetStockItemsRequest)(nil),     // 10: warehouse.v1.GetStockItemsRequest
	(*GetStockItemsReply)(nil),       // 11: warehouse.v1.GetStockItemsReply
	(*GetStockByProductRequest)(nil), // 12: warehouse.v1.GetStockByProductRequest
	(*GetStockByProductReply)(nil),   // 13: warehouse.v1.GetStockByProductReply
	(*ReceiptItem)(nil),              // 14: warehouse.v1.ReceiptItem
	(*CreateReceiptRequest)(nil),     // 15: warehouse.v1.CreateReceiptRequest
	(*CreateReceiptReply)(nil),       // 16: warehouse.v1.CreateReceiptReply
	(*TransferItem)(nil),             // 17: warehouse.v1.TransferItem
	(*CreateTransferRequest)(nil),    // 18: warehouse.v1.CreateTransferRequest
	(*CreateTransferReply)(nil),      // 19: warehouse.v1.CreateTransferReply
	(*WriteOffItem)(nil),             // 20: warehouse.v1.WriteOffItem
	(*CreateWriteOffRequest)(nil),    // 21: warehouse.v1.CreateWriteOffRequest
	(*CreateWriteOffReply)(nil),      // 22: warehouse.v1.CreateWriteOffReply
	(*GiftItem)(nil),                 // 23: warehouse.v1.GiftItem
	(*CreateGiftRequest)(nil),        // 24: warehouse.v1.CreateGiftRequest
	(*CreateGiftReply)(nil),          // 25: warehouse.v1.CreateGiftReply
	(*ListMovementsRequest)(nil),     // 26: warehouse.v1.ListMovementsRequest
	(*ListMovementsReply)(nil),       // 27: warehouse.v1.ListMovementsReply
	(*StartInventoryRequest)(nil),    // 28: warehouse.v1.StartInventoryRequest
	(*StartInventoryReply)(nil),      // 29: warehouse.v1.StartInventoryReply
	(*SetInventoryItemRequest)(nil),  // 30: warehouse.v1.SetInventoryItemRequest
	(*SetInventoryItemReply)(nil),    // 31: warehouse.v1.SetInventoryItemReply
	(*CompleteInventoryRequest)(nil), // 32: warehouse.v1.CompleteInventoryRequest
	(*CompleteInventoryReply)(nil),   // 33: warehouse.v1.CompleteInventoryReply
	(*GetInventoryRequest)(nil),      // 34: warehouse.v1.GetInventoryRequest
	(*GetInventoryReply)(nil),        // 35: warehouse.v1.GetInventoryReply
	(*SetMinQuantityRequest)(nil),    // 36: warehouse.v1.SetMinQuantityRequest
	(*SetMinQuantityReply)(nil),      // 37: warehouse.v1.SetMinQuantityReply
	(*GetLowStockItemsRequest)(nil),  // 38: warehouse.v1.GetLowStockItemsRequest
	(*GetLowStockItemsReply)(nil),    // 39: warehouse.v1.GetLowStockItemsReply
	(*Warehouse)(nil),                // 40: warehouse.v1.Warehouse
	(*v1.PaginateRequest)(nil),       // 41: utils.v1.PaginateRequest
	(*v1.PaginateReply)(nil),         // 42: utils.v1.PaginateReply
	(*StockItem)(nil),                // 43: warehouse.v1.StockItem
	(*StockMovement)(nil),            // 44: warehouse.v1.StockMovement
	(*Inventory)(nil),                // 45: warehouse.v1.Inventory
	(*InventoryItem)(nil),            // 46: warehouse.v1.InventoryItem
}
var file_api_warehouse_v1_warehouse_proto_depIdxs = []int32{
	40, // 0: warehouse.v1.CreateWarehouseReply.warehouse:type_name -> warehouse.v1.Warehouse
	40, // 1: warehouse.v1.GetWarehouseReply.warehouse:type_name -> warehouse.v1.Warehouse
	41, // 2: warehouse.v1.ListWarehousesRequest.paginate:type_name -> utils.v1.PaginateRequest
	40, // 3: warehouse.v1.ListWarehousesReply.items:type_name -> warehouse.v1.Warehouse
	42, // 4: warehouse.v1.ListWarehousesReply.paginate:type_name -> utils.v1.PaginateReply
	40, // 5: warehouse.v1.UpdateWarehouseReply.warehouse:type_name -> warehouse.v1.Warehouse
	41, // 6: warehouse.v1.GetStockItemsRequest.paginate:type_name -> utils.v1.PaginateRequest
	43, // 7: warehouse.v1.GetStockItemsReply.items:type_name -> warehouse.v1.StockItem
	42, // 8: warehouse.v1.GetStockItemsReply.paginate:type_name -> utils.v1.PaginateReply
	43, // 9: warehouse.v1.GetStockByProductReply.items:type_name -> warehouse.v1.StockItem
	14, // 10: warehouse.v1.CreateReceiptRequest.items:type_name -> warehouse.v1.ReceiptItem
	44, // 11: warehouse.v1.CreateReceiptReply.movements:type_name -> warehouse.v1.StockMovement
	17, // 12: warehouse.v1.CreateTransferRequest.items:type_name -> warehouse.v1.TransferItem
	44, // 13: warehouse.v1.CreateTransferReply.movements:type_name -> warehouse.v1.StockMovement
	20, // 14: warehouse.v1.CreateWriteOffRequest.items:type_name -> warehouse.v1.WriteOffItem
	44, // 15: warehouse.v1.CreateWriteOffReply.movements:type_name -> warehouse.v1.StockMovement
	23, // 16: warehouse.v1.CreateGiftRequest.items:type_name -> warehouse.v1.GiftItem
	44, // 17: warehouse.v1.CreateGiftReply.movements:type_name -> warehouse.v1.StockMovement
	41, // 18: warehouse.v1.ListMovementsRequest.paginate:type_name -> utils.v1.PaginateRequest
	44, // 19: warehouse.v1.ListMovementsReply.items:type_name -> warehouse.v1.StockMovement
	42, // 20: warehouse.v1.ListMovementsReply.paginate:type_name -> utils.v1.PaginateReply
	45, // 21: warehouse.v1.StartInventoryReply.inventory:type_name -> warehouse.v1.Inventory
	46, // 22: warehouse.v1.SetInventoryItemReply.item:type_name -> warehouse.v1.InventoryItem
	45, // 23: warehouse.v1.CompleteInventoryReply.inventory:type_name -> warehouse.v1.Inventory
	45, // 24: warehouse.v1.GetInventoryReply.inventory:type_name -> warehouse.v1.Inventory
	43, // 25: warehouse.v1.SetMinQuantityReply.item:type_name -> warehouse.v1.StockItem
	43, // 26: warehouse.v1.GetLowStockItemsReply.items:type_name -> warehouse.v1.StockItem
	0,  // 27: warehouse.v1.WarehouseService.CreateWarehouse:input_type -> warehouse.v1.CreateWarehouseRequest
	2,  // 28: warehouse.v1.WarehouseService.GetWarehouse:input_type -> warehouse.v1.GetWarehouseRequest
	4,  // 29: warehouse.v1.WarehouseService.ListWarehouses:input_type -> warehouse.v1.ListWarehousesRequest
	6,  // 30: warehouse.v1.WarehouseService.UpdateWarehouse:input_type -> warehouse.v1.UpdateWarehouseRequest
	8,  // 31: warehouse.v1.WarehouseService.DeleteWarehouse:input_type -> warehouse.v1.DeleteWarehouseRequest
	10, // 32: warehouse.v1.WarehouseService.GetStockItems:input_type -> warehouse.v1.GetStockItemsRequest
	12, // 33: warehouse.v1.WarehouseService.GetStockByProduct:input_type -> warehouse.v1.GetStockByProductRequest
	15, // 34: warehouse.v1.WarehouseService.CreateReceipt:input_type -> warehouse.v1.CreateReceiptRequest
	18, // 35: warehouse.v1.WarehouseService.CreateTransfer:input_type -> warehouse.v1.CreateTransferRequest
	21, // 36: warehouse.v1.WarehouseService.CreateWriteOff:input_type -> warehouse.v1.CreateWriteOffRequest
	24, // 37: warehouse.v1.WarehouseService.CreateGift:input_type -> warehouse.v1.CreateGiftRequest
	26, // 38: warehouse.v1.WarehouseService.ListMovements:input_type -> warehouse.v1.ListMovementsRequest
	36, // 39: warehouse.v1.WarehouseService.SetMinQuantity:input_type -> warehouse.v1.SetMinQuantityRequest
	38, // 40: warehouse.v1.WarehouseService.GetLowStockItems:input_type -> warehouse.v1.GetLowStockItemsRequest
	28, // 41: warehouse.v1.WarehouseService.StartInventory:input_type -> warehouse.v1.StartInventoryRequest
	30, // 42: warehouse.v1.WarehouseService.SetInventoryItem:input_type -> warehouse.v1.SetInventoryItemRequest
	32, // 43: warehouse.v1.WarehouseService.CompleteInventory:input_type -> warehouse.v1.CompleteInventoryRequest
	34, // 44: warehouse.v1.WarehouseService.GetInventory:input_type -> warehouse.v1.GetInventoryRequest
	1,  // 45: warehouse.v1.WarehouseService.CreateWarehouse:output_type -> warehouse.v1.CreateWarehouseReply
	3,  // 46: warehouse.v1.WarehouseService.GetWarehouse:output_type -> warehouse.v1.GetWarehouseReply
	5,  // 47: warehouse.v1.WarehouseService.ListWarehouses:output_type -> warehouse.v1.ListWarehousesReply
	7,  // 48: warehouse.v1.WarehouseService.UpdateWarehouse:output_type -> warehouse.v1.UpdateWarehouseReply
	9,  // 49: warehouse.v1.WarehouseService.DeleteWarehouse:output_type -> warehouse.v1.DeleteWarehouseReply
	11, // 50: warehouse.v1.WarehouseService.GetStockItems:output_type -> warehouse.v1.GetStockItemsReply
	13, // 51: warehouse.v1.WarehouseService.GetStockByProduct:output_type -> warehouse.v1.GetStockByProductReply
	16, // 52: warehouse.v1.WarehouseService.CreateReceipt:output_type -> warehouse.v1.CreateReceiptReply
	19, // 53: warehouse.v1.WarehouseService.CreateTransfer:output_type -> warehouse.v1.CreateTransferReply
	22, // 54: warehouse.v1.WarehouseService.CreateWriteOff:output_type -> warehouse.v1.CreateWriteOffReply
	25, // 55: warehouse.v1.WarehouseService.CreateGift:output_type -> warehouse.v1.CreateGiftReply
	27, // 56: warehouse.v1.WarehouseService.ListMovements:output_type -> warehouse.v1.ListMovementsReply
	37, // 57: warehouse.v1.WarehouseService.SetMinQuantity:output_type -> warehouse.v1.SetMinQuantityReply
	39, // 58: warehouse.v1.WarehouseService.GetLowStockItems:output_type -> warehouse.v1.GetLowStockItemsReply
	29, // 59: warehouse.v1.WarehouseService.StartInventory:output_type -> warehouse.v1.StartInventoryReply
	31, // 60: warehouse.v1.WarehouseService.SetInventoryItem:output_type -> warehouse.v1.SetInventoryItemReply
	33, // 61: warehouse.v1.WarehouseService.CompleteInventory:output_type -> warehouse.v1.CompleteInventoryReply
	35, // 62: warehouse.v1.WarehouseService.GetInventory:output_type -> warehouse.v1.GetInventoryReply
	45, // [45:63] is the sub-list for method output_type
	27, // [27:45] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_api_warehouse_v1_warehouse_proto_init() }
func file_api_warehouse_v1_warehouse_proto_init() {
	if File_api_warehouse_v1_warehouse_proto != nil {
		return
	}
	file_api_warehouse_v1_models_proto_init()
	file_api_warehouse_v1_warehouse_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_warehouse_v1_warehouse_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_warehouse_v1_warehouse_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_warehouse_v1_warehouse_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_warehouse_v1_warehouse_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_warehouse_v1_warehouse_proto_rawDesc), len(file_api_warehouse_v1_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_warehouse_v1_warehouse_proto_goTypes,
		DependencyIndexes: file_api_warehouse_v1_warehouse_proto_depIdxs,
		MessageInfos:      file_api_warehouse_v1_warehouse_proto_msgTypes,
	}.Build()
	File_api_warehouse_v1_warehouse_proto = out.File
	file_api_warehouse_v1_warehouse_proto_goTypes = nil
	file_api_warehouse_v1_warehouse_proto_depIdxs = nil
}
