// Code generated by ent, DO NOT EDIT.

package warehouse

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"gitlab.calendaria.team/services/warehouse/ent/enum"
)

const (
	// Label holds the string label denoting the warehouse type in the database.
	Label = "warehouse"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldStoreID holds the string denoting the store_id field in the database.
	FieldStoreID = "store_id"
	// EdgeStockItems holds the string denoting the stock_items edge name in mutations.
	EdgeStockItems = "stock_items"
	// EdgeStockMovements holds the string denoting the stock_movements edge name in mutations.
	EdgeStockMovements = "stock_movements"
	// EdgeInventories holds the string denoting the inventories edge name in mutations.
	EdgeInventories = "inventories"
	// Table holds the table name of the warehouse in the database.
	Table = "warehouses"
	// StockItemsTable is the table that holds the stock_items relation/edge.
	StockItemsTable = "stock_items"
	// StockItemsInverseTable is the table name for the StockItem entity.
	// It exists in this package in order to avoid circular dependency with the "stockitem" package.
	StockItemsInverseTable = "stock_items"
	// StockItemsColumn is the table column denoting the stock_items relation/edge.
	StockItemsColumn = "warehouse_id"
	// StockMovementsTable is the table that holds the stock_movements relation/edge.
	StockMovementsTable = "stock_movements"
	// StockMovementsInverseTable is the table name for the StockMovement entity.
	// It exists in this package in order to avoid circular dependency with the "stockmovement" package.
	StockMovementsInverseTable = "stock_movements"
	// StockMovementsColumn is the table column denoting the stock_movements relation/edge.
	StockMovementsColumn = "warehouse_id"
	// InventoriesTable is the table that holds the inventories relation/edge.
	InventoriesTable = "inventories"
	// InventoriesInverseTable is the table name for the Inventory entity.
	// It exists in this package in order to avoid circular dependency with the "inventory" package.
	InventoriesInverseTable = "inventories"
	// InventoriesColumn is the table column denoting the inventories relation/edge.
	InventoriesColumn = "warehouse_id"
)

// Columns holds all SQL columns for warehouse fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldTenantID,
	FieldName,
	FieldType,
	FieldDescription,
	FieldAddress,
	FieldIsActive,
	FieldStoreID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "gitlab.calendaria.team/services/warehouse/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultAddress holds the default value on creation for the "address" field.
	DefaultAddress string
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
)

const DefaultType enum.WarehouseType = "MAIN"

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type enum.WarehouseType) error {
	switch _type {
	case "MAIN", "HALL", "TRANSIT":
		return nil
	default:
		return fmt.Errorf("warehouse: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Warehouse queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByStoreID orders the results by the store_id field.
func ByStoreID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoreID, opts...).ToFunc()
}

// ByStockItemsCount orders the results by stock_items count.
func ByStockItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStockItemsStep(), opts...)
	}
}

// ByStockItems orders the results by stock_items terms.
func ByStockItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStockItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByStockMovementsCount orders the results by stock_movements count.
func ByStockMovementsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStockMovementsStep(), opts...)
	}
}

// ByStockMovements orders the results by stock_movements terms.
func ByStockMovements(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStockMovementsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInventoriesCount orders the results by inventories count.
func ByInventoriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInventoriesStep(), opts...)
	}
}

// ByInventories orders the results by inventories terms.
func ByInventories(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInventoriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStockItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StockItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StockItemsTable, StockItemsColumn),
	)
}
func newStockMovementsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StockMovementsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StockMovementsTable, StockMovementsColumn),
	)
}
func newInventoriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InventoriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InventoriesTable, InventoriesColumn),
	)
}
