services:
  warehouse:
    build: .
    container_name: warehouse
    restart: unless-stopped
    environment:
      - SERVICE_NAME=warehouse
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - DEBUG=${DEBUG}
      - AUTOMIGRATE=${AUTOMIGRATE}
