// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"gitlab.calendaria.team/services/warehouse/ent/inventory"
	"gitlab.calendaria.team/services/warehouse/ent/schema"
	"gitlab.calendaria.team/services/warehouse/ent/stockitem"
	"gitlab.calendaria.team/services/warehouse/ent/stockmovement"
	"gitlab.calendaria.team/services/warehouse/ent/warehouse"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	inventoryFields := schema.Inventory{}.Fields()
	_ = inventoryFields
	// inventoryDescCreatedAt is the schema descriptor for created_at field.
	inventoryDescCreatedAt := inventoryFields[5].Descriptor()
	// inventory.DefaultCreatedAt holds the default value on creation for the created_at field.
	inventory.DefaultCreatedAt = inventoryDescCreatedAt.Default.(func() time.Time)
	stockitemMixin := schema.StockItem{}.Mixin()
	stockitemMixinFields0 := stockitemMixin[0].Fields()
	_ = stockitemMixinFields0
	stockitemFields := schema.StockItem{}.Fields()
	_ = stockitemFields
	// stockitemDescCreatedAt is the schema descriptor for created_at field.
	stockitemDescCreatedAt := stockitemMixinFields0[0].Descriptor()
	// stockitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	stockitem.DefaultCreatedAt = stockitemDescCreatedAt.Default.(func() time.Time)
	// stockitemDescUpdatedAt is the schema descriptor for updated_at field.
	stockitemDescUpdatedAt := stockitemMixinFields0[1].Descriptor()
	// stockitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	stockitem.DefaultUpdatedAt = stockitemDescUpdatedAt.Default.(func() time.Time)
	// stockitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	stockitem.UpdateDefaultUpdatedAt = stockitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	stockmovementFields := schema.StockMovement{}.Fields()
	_ = stockmovementFields
	// stockmovementDescCreatedAt is the schema descriptor for created_at field.
	stockmovementDescCreatedAt := stockmovementFields[9].Descriptor()
	// stockmovement.DefaultCreatedAt holds the default value on creation for the created_at field.
	stockmovement.DefaultCreatedAt = stockmovementDescCreatedAt.Default.(func() time.Time)
	warehouseMixin := schema.Warehouse{}.Mixin()
	warehouseMixinHooks1 := warehouseMixin[1].Hooks()
	warehouse.Hooks[0] = warehouseMixinHooks1[0]
	warehouseMixinInters1 := warehouseMixin[1].Interceptors()
	warehouse.Interceptors[0] = warehouseMixinInters1[0]
	warehouseMixinFields0 := warehouseMixin[0].Fields()
	_ = warehouseMixinFields0
	warehouseFields := schema.Warehouse{}.Fields()
	_ = warehouseFields
	// warehouseDescCreatedAt is the schema descriptor for created_at field.
	warehouseDescCreatedAt := warehouseMixinFields0[0].Descriptor()
	// warehouse.DefaultCreatedAt holds the default value on creation for the created_at field.
	warehouse.DefaultCreatedAt = warehouseDescCreatedAt.Default.(func() time.Time)
	// warehouseDescUpdatedAt is the schema descriptor for updated_at field.
	warehouseDescUpdatedAt := warehouseMixinFields0[1].Descriptor()
	// warehouse.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	warehouse.DefaultUpdatedAt = warehouseDescUpdatedAt.Default.(func() time.Time)
	// warehouse.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	warehouse.UpdateDefaultUpdatedAt = warehouseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// warehouseDescName is the schema descriptor for name field.
	warehouseDescName := warehouseFields[2].Descriptor()
	// warehouse.NameValidator is a validator for the "name" field. It is called by the builders before save.
	warehouse.NameValidator = warehouseDescName.Validators[0].(func(string) error)
	// warehouseDescDescription is the schema descriptor for description field.
	warehouseDescDescription := warehouseFields[4].Descriptor()
	// warehouse.DefaultDescription holds the default value on creation for the description field.
	warehouse.DefaultDescription = warehouseDescDescription.Default.(string)
	// warehouseDescAddress is the schema descriptor for address field.
	warehouseDescAddress := warehouseFields[5].Descriptor()
	// warehouse.DefaultAddress holds the default value on creation for the address field.
	warehouse.DefaultAddress = warehouseDescAddress.Default.(string)
	// warehouseDescIsActive is the schema descriptor for is_active field.
	warehouseDescIsActive := warehouseFields[6].Descriptor()
	// warehouse.DefaultIsActive holds the default value on creation for the is_active field.
	warehouse.DefaultIsActive = warehouseDescIsActive.Default.(bool)
}

const (
	Version = "v0.14.0"                                         // Version of ent codegen.
	Sum     = "h1:EO3Z9aZ5bXJatJeGqu/EVdnNr6K4mRq3rWe5owt0MC4=" // Sum of ent codegen.
)
