// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/warehouse/internal/biz"
	"gitlab.calendaria.team/services/warehouse/internal/conf"
	"gitlab.calendaria.team/services/warehouse/internal/data"
	"gitlab.calendaria.team/services/warehouse/internal/server"
	"gitlab.calendaria.team/services/warehouse/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	warehousesRepo := data.NewWarehousesRepo(dataData)
	stockItemsRepo := data.NewStockItemsRepo(dataData)
	stockMovementsRepo := data.NewStockMovementsRepo(dataData)
	inventoriesRepo := data.NewInventoriesRepo(dataData)
	conn, cleanup2, err := data.NewNatsClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	lowStockPublisher := data.NewLowStockPublisher(conn, logger)
	warehouseUsecase := biz.NewWarehouseUsecase(logger, warehousesRepo, stockItemsRepo, stockMovementsRepo, inventoriesRepo, lowStockPublisher)

	// Start NATS consumer for sales and order events
	_, consumerCleanup, err := biz.NewConsumer(conn, warehouseUsecase, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}

	warehouseService := service.NewWarehouseService(warehouseUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, warehouseService)
	app := newApp(logger, grpcServer)
	return app, func() {
		consumerCleanup()
		cleanup2()
		cleanup()
	}, nil
}
