// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/warehouse/ent/enum"
	"gitlab.calendaria.team/services/warehouse/ent/inventory"
	"gitlab.calendaria.team/services/warehouse/ent/inventoryitem"
	"gitlab.calendaria.team/services/warehouse/ent/warehouse"
)

// InventoryCreate is the builder for creating a Inventory entity.
type InventoryCreate struct {
	config
	mutation *InventoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (ic *InventoryCreate) SetTenantID(i int64) *InventoryCreate {
	ic.mutation.SetTenantID(i)
	return ic
}

// SetWarehouseID sets the "warehouse_id" field.
func (ic *InventoryCreate) SetWarehouseID(i int64) *InventoryCreate {
	ic.mutation.SetWarehouseID(i)
	return ic
}

// SetStatus sets the "status" field.
func (ic *InventoryCreate) SetStatus(es enum.InventoryStatus) *InventoryCreate {
	ic.mutation.SetStatus(es)
	return ic
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ic *InventoryCreate) SetNillableStatus(es *enum.InventoryStatus) *InventoryCreate {
	if es != nil {
		ic.SetStatus(*es)
	}
	return ic
}

// SetCreatedBy sets the "created_by" field.
func (ic *InventoryCreate) SetCreatedBy(i int64) *InventoryCreate {
	ic.mutation.SetCreatedBy(i)
	return ic
}

// SetCreatedAt sets the "created_at" field.
func (ic *InventoryCreate) SetCreatedAt(t time.Time) *InventoryCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ic *InventoryCreate) SetNillableCreatedAt(t *time.Time) *InventoryCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetCompletedAt sets the "completed_at" field.
func (ic *InventoryCreate) SetCompletedAt(t time.Time) *InventoryCreate {
	ic.mutation.SetCompletedAt(t)
	return ic
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (ic *InventoryCreate) SetNillableCompletedAt(t *time.Time) *InventoryCreate {
	if t != nil {
		ic.SetCompletedAt(*t)
	}
	return ic
}

// SetID sets the "id" field.
func (ic *InventoryCreate) SetID(i int64) *InventoryCreate {
	ic.mutation.SetID(i)
	return ic
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (ic *InventoryCreate) SetWarehouse(w *Warehouse) *InventoryCreate {
	return ic.SetWarehouseID(w.ID)
}

// AddItemIDs adds the "items" edge to the InventoryItem entity by IDs.
func (ic *InventoryCreate) AddItemIDs(ids ...int64) *InventoryCreate {
	ic.mutation.AddItemIDs(ids...)
	return ic
}

// AddItems adds the "items" edges to the InventoryItem entity.
func (ic *InventoryCreate) AddItems(i ...*InventoryItem) *InventoryCreate {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ic.AddItemIDs(ids...)
}

// Mutation returns the InventoryMutation object of the builder.
func (ic *InventoryCreate) Mutation() *InventoryMutation {
	return ic.mutation
}

// Save creates the Inventory in the database.
func (ic *InventoryCreate) Save(ctx context.Context) (*Inventory, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InventoryCreate) SaveX(ctx context.Context) *Inventory {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *InventoryCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *InventoryCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *InventoryCreate) defaults() {
	if _, ok := ic.mutation.Status(); !ok {
		v := inventory.DefaultStatus
		ic.mutation.SetStatus(v)
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := inventory.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InventoryCreate) check() error {
	if _, ok := ic.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Inventory.tenant_id"`)}
	}
	if _, ok := ic.mutation.WarehouseID(); !ok {
		return &ValidationError{Name: "warehouse_id", err: errors.New(`ent: missing required field "Inventory.warehouse_id"`)}
	}
	if _, ok := ic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Inventory.status"`)}
	}
	if v, ok := ic.mutation.Status(); ok {
		if err := inventory.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Inventory.status": %w`, err)}
		}
	}
	if _, ok := ic.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Inventory.created_by"`)}
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Inventory.created_at"`)}
	}
	if len(ic.mutation.WarehouseIDs()) == 0 {
		return &ValidationError{Name: "warehouse", err: errors.New(`ent: missing required edge "Inventory.warehouse"`)}
	}
	return nil
}

func (ic *InventoryCreate) sqlSave(ctx context.Context) (*Inventory, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *InventoryCreate) createSpec() (*Inventory, *sqlgraph.CreateSpec) {
	var (
		_node = &Inventory{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(inventory.Table, sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = ic.conflict
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ic.mutation.TenantID(); ok {
		_spec.SetField(inventory.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := ic.mutation.Status(); ok {
		_spec.SetField(inventory.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := ic.mutation.CreatedBy(); ok {
		_spec.SetField(inventory.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.SetField(inventory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ic.mutation.CompletedAt(); ok {
		_spec.SetField(inventory.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if nodes := ic.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inventory.WarehouseTable,
			Columns: []string{inventory.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WarehouseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.ItemsTable,
			Columns: []string{inventory.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Inventory.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventoryUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (ic *InventoryCreate) OnConflict(opts ...sql.ConflictOption) *InventoryUpsertOne {
	ic.conflict = opts
	return &InventoryUpsertOne{
		create: ic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Inventory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ic *InventoryCreate) OnConflictColumns(columns ...string) *InventoryUpsertOne {
	ic.conflict = append(ic.conflict, sql.ConflictColumns(columns...))
	return &InventoryUpsertOne{
		create: ic,
	}
}

type (
	// InventoryUpsertOne is the builder for "upsert"-ing
	//  one Inventory node.
	InventoryUpsertOne struct {
		create *InventoryCreate
	}

	// InventoryUpsert is the "OnConflict" setter.
	InventoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetStatus sets the "status" field.
func (u *InventoryUpsert) SetStatus(v enum.InventoryStatus) *InventoryUpsert {
	u.Set(inventory.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateStatus() *InventoryUpsert {
	u.SetExcluded(inventory.FieldStatus)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *InventoryUpsert) SetCompletedAt(v time.Time) *InventoryUpsert {
	u.Set(inventory.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateCompletedAt() *InventoryUpsert {
	u.SetExcluded(inventory.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *InventoryUpsert) ClearCompletedAt() *InventoryUpsert {
	u.SetNull(inventory.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Inventory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inventory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InventoryUpsertOne) UpdateNewValues() *InventoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(inventory.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(inventory.FieldTenantID)
		}
		if _, exists := u.create.mutation.WarehouseID(); exists {
			s.SetIgnore(inventory.FieldWarehouseID)
		}
		if _, exists := u.create.mutation.CreatedBy(); exists {
			s.SetIgnore(inventory.FieldCreatedBy)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(inventory.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Inventory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InventoryUpsertOne) Ignore() *InventoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventoryUpsertOne) DoNothing() *InventoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventoryCreate.OnConflict
// documentation for more info.
func (u *InventoryUpsertOne) Update(set func(*InventoryUpsert)) *InventoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *InventoryUpsertOne) SetStatus(v enum.InventoryStatus) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateStatus() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateStatus()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *InventoryUpsertOne) SetCompletedAt(v time.Time) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateCompletedAt() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *InventoryUpsertOne) ClearCompletedAt() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *InventoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InventoryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InventoryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InventoryCreateBulk is the builder for creating many Inventory entities in bulk.
type InventoryCreateBulk struct {
	config
	err      error
	builders []*InventoryCreate
	conflict []sql.ConflictOption
}

// Save creates the Inventory entities in the database.
func (icb *InventoryCreateBulk) Save(ctx context.Context) ([]*Inventory, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Inventory, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = icb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InventoryCreateBulk) SaveX(ctx context.Context) []*Inventory {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *InventoryCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *InventoryCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Inventory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventoryUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (icb *InventoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *InventoryUpsertBulk {
	icb.conflict = opts
	return &InventoryUpsertBulk{
		create: icb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Inventory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (icb *InventoryCreateBulk) OnConflictColumns(columns ...string) *InventoryUpsertBulk {
	icb.conflict = append(icb.conflict, sql.ConflictColumns(columns...))
	return &InventoryUpsertBulk{
		create: icb,
	}
}

// InventoryUpsertBulk is the builder for "upsert"-ing
// a bulk of Inventory nodes.
type InventoryUpsertBulk struct {
	create *InventoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Inventory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inventory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InventoryUpsertBulk) UpdateNewValues() *InventoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(inventory.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(inventory.FieldTenantID)
			}
			if _, exists := b.mutation.WarehouseID(); exists {
				s.SetIgnore(inventory.FieldWarehouseID)
			}
			if _, exists := b.mutation.CreatedBy(); exists {
				s.SetIgnore(inventory.FieldCreatedBy)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(inventory.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Inventory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InventoryUpsertBulk) Ignore() *InventoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventoryUpsertBulk) DoNothing() *InventoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventoryCreateBulk.OnConflict
// documentation for more info.
func (u *InventoryUpsertBulk) Update(set func(*InventoryUpsert)) *InventoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *InventoryUpsertBulk) SetStatus(v enum.InventoryStatus) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateStatus() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateStatus()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *InventoryUpsertBulk) SetCompletedAt(v time.Time) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateCompletedAt() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *InventoryUpsertBulk) ClearCompletedAt() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *InventoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InventoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
