// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/warehouse/ent/inventory"
	"github.com/makesalekz/warehouse/ent/inventoryitem"
)

// InventoryItemCreate is the builder for creating a InventoryItem entity.
type InventoryItemCreate struct {
	config
	mutation *InventoryItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInventoryID sets the "inventory_id" field.
func (iic *InventoryItemCreate) SetInventoryID(i int64) *InventoryItemCreate {
	iic.mutation.SetInventoryID(i)
	return iic
}

// SetProductID sets the "product_id" field.
func (iic *InventoryItemCreate) SetProductID(i int64) *InventoryItemCreate {
	iic.mutation.SetProductID(i)
	return iic
}

// SetExpectedQty sets the "expected_qty" field.
func (iic *InventoryItemCreate) SetExpectedQty(d decimal.Decimal) *InventoryItemCreate {
	iic.mutation.SetExpectedQty(d)
	return iic
}

// SetActualQty sets the "actual_qty" field.
func (iic *InventoryItemCreate) SetActualQty(d decimal.Decimal) *InventoryItemCreate {
	iic.mutation.SetActualQty(d)
	return iic
}

// SetNillableActualQty sets the "actual_qty" field if the given value is not nil.
func (iic *InventoryItemCreate) SetNillableActualQty(d *decimal.Decimal) *InventoryItemCreate {
	if d != nil {
		iic.SetActualQty(*d)
	}
	return iic
}

// SetDifference sets the "difference" field.
func (iic *InventoryItemCreate) SetDifference(d decimal.Decimal) *InventoryItemCreate {
	iic.mutation.SetDifference(d)
	return iic
}

// SetNillableDifference sets the "difference" field if the given value is not nil.
func (iic *InventoryItemCreate) SetNillableDifference(d *decimal.Decimal) *InventoryItemCreate {
	if d != nil {
		iic.SetDifference(*d)
	}
	return iic
}

// SetID sets the "id" field.
func (iic *InventoryItemCreate) SetID(i int64) *InventoryItemCreate {
	iic.mutation.SetID(i)
	return iic
}

// SetInventory sets the "inventory" edge to the Inventory entity.
func (iic *InventoryItemCreate) SetInventory(i *Inventory) *InventoryItemCreate {
	return iic.SetInventoryID(i.ID)
}

// Mutation returns the InventoryItemMutation object of the builder.
func (iic *InventoryItemCreate) Mutation() *InventoryItemMutation {
	return iic.mutation
}

// Save creates the InventoryItem in the database.
func (iic *InventoryItemCreate) Save(ctx context.Context) (*InventoryItem, error) {
	return withHooks(ctx, iic.sqlSave, iic.mutation, iic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (iic *InventoryItemCreate) SaveX(ctx context.Context) *InventoryItem {
	v, err := iic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iic *InventoryItemCreate) Exec(ctx context.Context) error {
	_, err := iic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iic *InventoryItemCreate) ExecX(ctx context.Context) {
	if err := iic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iic *InventoryItemCreate) check() error {
	if _, ok := iic.mutation.InventoryID(); !ok {
		return &ValidationError{Name: "inventory_id", err: errors.New(`ent: missing required field "InventoryItem.inventory_id"`)}
	}
	if _, ok := iic.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "InventoryItem.product_id"`)}
	}
	if _, ok := iic.mutation.ExpectedQty(); !ok {
		return &ValidationError{Name: "expected_qty", err: errors.New(`ent: missing required field "InventoryItem.expected_qty"`)}
	}
	if len(iic.mutation.InventoryIDs()) == 0 {
		return &ValidationError{Name: "inventory", err: errors.New(`ent: missing required edge "InventoryItem.inventory"`)}
	}
	return nil
}

func (iic *InventoryItemCreate) sqlSave(ctx context.Context) (*InventoryItem, error) {
	if err := iic.check(); err != nil {
		return nil, err
	}
	_node, _spec := iic.createSpec()
	if err := sqlgraph.CreateNode(ctx, iic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	iic.mutation.id = &_node.ID
	iic.mutation.done = true
	return _node, nil
}

func (iic *InventoryItemCreate) createSpec() (*InventoryItem, *sqlgraph.CreateSpec) {
	var (
		_node = &InventoryItem{config: iic.config}
		_spec = sqlgraph.NewCreateSpec(inventoryitem.Table, sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = iic.conflict
	if id, ok := iic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := iic.mutation.ProductID(); ok {
		_spec.SetField(inventoryitem.FieldProductID, field.TypeInt64, value)
		_node.ProductID = value
	}
	if value, ok := iic.mutation.ExpectedQty(); ok {
		_spec.SetField(inventoryitem.FieldExpectedQty, field.TypeFloat64, value)
		_node.ExpectedQty = value
	}
	if value, ok := iic.mutation.ActualQty(); ok {
		_spec.SetField(inventoryitem.FieldActualQty, field.TypeFloat64, value)
		_node.ActualQty = &value
	}
	if value, ok := iic.mutation.Difference(); ok {
		_spec.SetField(inventoryitem.FieldDifference, field.TypeFloat64, value)
		_node.Difference = &value
	}
	if nodes := iic.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inventoryitem.InventoryTable,
			Columns: []string{inventoryitem.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InventoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InventoryItem.Create().
//		SetInventoryID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventoryItemUpsert) {
//			SetInventoryID(v+v).
//		}).
//		Exec(ctx)
func (iic *InventoryItemCreate) OnConflict(opts ...sql.ConflictOption) *InventoryItemUpsertOne {
	iic.conflict = opts
	return &InventoryItemUpsertOne{
		create: iic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (iic *InventoryItemCreate) OnConflictColumns(columns ...string) *InventoryItemUpsertOne {
	iic.conflict = append(iic.conflict, sql.ConflictColumns(columns...))
	return &InventoryItemUpsertOne{
		create: iic,
	}
}

type (
	// InventoryItemUpsertOne is the builder for "upsert"-ing
	//  one InventoryItem node.
	InventoryItemUpsertOne struct {
		create *InventoryItemCreate
	}

	// InventoryItemUpsert is the "OnConflict" setter.
	InventoryItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetActualQty sets the "actual_qty" field.
func (u *InventoryItemUpsert) SetActualQty(v decimal.Decimal) *InventoryItemUpsert {
	u.Set(inventoryitem.FieldActualQty, v)
	return u
}

// UpdateActualQty sets the "actual_qty" field to the value that was provided on create.
func (u *InventoryItemUpsert) UpdateActualQty() *InventoryItemUpsert {
	u.SetExcluded(inventoryitem.FieldActualQty)
	return u
}

// AddActualQty adds v to the "actual_qty" field.
func (u *InventoryItemUpsert) AddActualQty(v decimal.Decimal) *InventoryItemUpsert {
	u.Add(inventoryitem.FieldActualQty, v)
	return u
}

// ClearActualQty clears the value of the "actual_qty" field.
func (u *InventoryItemUpsert) ClearActualQty() *InventoryItemUpsert {
	u.SetNull(inventoryitem.FieldActualQty)
	return u
}

// SetDifference sets the "difference" field.
func (u *InventoryItemUpsert) SetDifference(v decimal.Decimal) *InventoryItemUpsert {
	u.Set(inventoryitem.FieldDifference, v)
	return u
}

// UpdateDifference sets the "difference" field to the value that was provided on create.
func (u *InventoryItemUpsert) UpdateDifference() *InventoryItemUpsert {
	u.SetExcluded(inventoryitem.FieldDifference)
	return u
}

// AddDifference adds v to the "difference" field.
func (u *InventoryItemUpsert) AddDifference(v decimal.Decimal) *InventoryItemUpsert {
	u.Add(inventoryitem.FieldDifference, v)
	return u
}

// ClearDifference clears the value of the "difference" field.
func (u *InventoryItemUpsert) ClearDifference() *InventoryItemUpsert {
	u.SetNull(inventoryitem.FieldDifference)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inventoryitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InventoryItemUpsertOne) UpdateNewValues() *InventoryItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(inventoryitem.FieldID)
		}
		if _, exists := u.create.mutation.InventoryID(); exists {
			s.SetIgnore(inventoryitem.FieldInventoryID)
		}
		if _, exists := u.create.mutation.ProductID(); exists {
			s.SetIgnore(inventoryitem.FieldProductID)
		}
		if _, exists := u.create.mutation.ExpectedQty(); exists {
			s.SetIgnore(inventoryitem.FieldExpectedQty)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InventoryItemUpsertOne) Ignore() *InventoryItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventoryItemUpsertOne) DoNothing() *InventoryItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventoryItemCreate.OnConflict
// documentation for more info.
func (u *InventoryItemUpsertOne) Update(set func(*InventoryItemUpsert)) *InventoryItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventoryItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetActualQty sets the "actual_qty" field.
func (u *InventoryItemUpsertOne) SetActualQty(v decimal.Decimal) *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.SetActualQty(v)
	})
}

// AddActualQty adds v to the "actual_qty" field.
func (u *InventoryItemUpsertOne) AddActualQty(v decimal.Decimal) *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.AddActualQty(v)
	})
}

// UpdateActualQty sets the "actual_qty" field to the value that was provided on create.
func (u *InventoryItemUpsertOne) UpdateActualQty() *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.UpdateActualQty()
	})
}

// ClearActualQty clears the value of the "actual_qty" field.
func (u *InventoryItemUpsertOne) ClearActualQty() *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.ClearActualQty()
	})
}

// SetDifference sets the "difference" field.
func (u *InventoryItemUpsertOne) SetDifference(v decimal.Decimal) *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.SetDifference(v)
	})
}

// AddDifference adds v to the "difference" field.
func (u *InventoryItemUpsertOne) AddDifference(v decimal.Decimal) *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.AddDifference(v)
	})
}

// UpdateDifference sets the "difference" field to the value that was provided on create.
func (u *InventoryItemUpsertOne) UpdateDifference() *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.UpdateDifference()
	})
}

// ClearDifference clears the value of the "difference" field.
func (u *InventoryItemUpsertOne) ClearDifference() *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.ClearDifference()
	})
}

// Exec executes the query.
func (u *InventoryItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventoryItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventoryItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InventoryItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InventoryItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InventoryItemCreateBulk is the builder for creating many InventoryItem entities in bulk.
type InventoryItemCreateBulk struct {
	config
	err      error
	builders []*InventoryItemCreate
	conflict []sql.ConflictOption
}

// Save creates the InventoryItem entities in the database.
func (iicb *InventoryItemCreateBulk) Save(ctx context.Context) ([]*InventoryItem, error) {
	if iicb.err != nil {
		return nil, iicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(iicb.builders))
	nodes := make([]*InventoryItem, len(iicb.builders))
	mutators := make([]Mutator, len(iicb.builders))
	for i := range iicb.builders {
		func(i int, root context.Context) {
			builder := iicb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, iicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = iicb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, iicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, iicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (iicb *InventoryItemCreateBulk) SaveX(ctx context.Context) []*InventoryItem {
	v, err := iicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iicb *InventoryItemCreateBulk) Exec(ctx context.Context) error {
	_, err := iicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iicb *InventoryItemCreateBulk) ExecX(ctx context.Context) {
	if err := iicb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InventoryItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventoryItemUpsert) {
//			SetInventoryID(v+v).
//		}).
//		Exec(ctx)
func (iicb *InventoryItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *InventoryItemUpsertBulk {
	iicb.conflict = opts
	return &InventoryItemUpsertBulk{
		create: iicb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (iicb *InventoryItemCreateBulk) OnConflictColumns(columns ...string) *InventoryItemUpsertBulk {
	iicb.conflict = append(iicb.conflict, sql.ConflictColumns(columns...))
	return &InventoryItemUpsertBulk{
		create: iicb,
	}
}

// InventoryItemUpsertBulk is the builder for "upsert"-ing
// a bulk of InventoryItem nodes.
type InventoryItemUpsertBulk struct {
	create *InventoryItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inventoryitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InventoryItemUpsertBulk) UpdateNewValues() *InventoryItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(inventoryitem.FieldID)
			}
			if _, exists := b.mutation.InventoryID(); exists {
				s.SetIgnore(inventoryitem.FieldInventoryID)
			}
			if _, exists := b.mutation.ProductID(); exists {
				s.SetIgnore(inventoryitem.FieldProductID)
			}
			if _, exists := b.mutation.ExpectedQty(); exists {
				s.SetIgnore(inventoryitem.FieldExpectedQty)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InventoryItemUpsertBulk) Ignore() *InventoryItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventoryItemUpsertBulk) DoNothing() *InventoryItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventoryItemCreateBulk.OnConflict
// documentation for more info.
func (u *InventoryItemUpsertBulk) Update(set func(*InventoryItemUpsert)) *InventoryItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventoryItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetActualQty sets the "actual_qty" field.
func (u *InventoryItemUpsertBulk) SetActualQty(v decimal.Decimal) *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.SetActualQty(v)
	})
}

// AddActualQty adds v to the "actual_qty" field.
func (u *InventoryItemUpsertBulk) AddActualQty(v decimal.Decimal) *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.AddActualQty(v)
	})
}

// UpdateActualQty sets the "actual_qty" field to the value that was provided on create.
func (u *InventoryItemUpsertBulk) UpdateActualQty() *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.UpdateActualQty()
	})
}

// ClearActualQty clears the value of the "actual_qty" field.
func (u *InventoryItemUpsertBulk) ClearActualQty() *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.ClearActualQty()
	})
}

// SetDifference sets the "difference" field.
func (u *InventoryItemUpsertBulk) SetDifference(v decimal.Decimal) *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.SetDifference(v)
	})
}

// AddDifference adds v to the "difference" field.
func (u *InventoryItemUpsertBulk) AddDifference(v decimal.Decimal) *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.AddDifference(v)
	})
}

// UpdateDifference sets the "difference" field to the value that was provided on create.
func (u *InventoryItemUpsertBulk) UpdateDifference() *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.UpdateDifference()
	})
}

// ClearDifference clears the value of the "difference" field.
func (u *InventoryItemUpsertBulk) ClearDifference() *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.ClearDifference()
	})
}

// Exec executes the query.
func (u *InventoryItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InventoryItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventoryItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventoryItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
