// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/warehouse/ent/enum"
	"gitlab.calendaria.team/services/warehouse/ent/inventory"
	"gitlab.calendaria.team/services/warehouse/ent/inventoryitem"
	"gitlab.calendaria.team/services/warehouse/ent/predicate"
)

// InventoryUpdate is the builder for updating Inventory entities.
type InventoryUpdate struct {
	config
	hooks     []Hook
	mutation  *InventoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the InventoryUpdate builder.
func (iu *InventoryUpdate) Where(ps ...predicate.Inventory) *InventoryUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetStatus sets the "status" field.
func (iu *InventoryUpdate) SetStatus(es enum.InventoryStatus) *InventoryUpdate {
	iu.mutation.SetStatus(es)
	return iu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (iu *InventoryUpdate) SetNillableStatus(es *enum.InventoryStatus) *InventoryUpdate {
	if es != nil {
		iu.SetStatus(*es)
	}
	return iu
}

// SetCompletedAt sets the "completed_at" field.
func (iu *InventoryUpdate) SetCompletedAt(t time.Time) *InventoryUpdate {
	iu.mutation.SetCompletedAt(t)
	return iu
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (iu *InventoryUpdate) SetNillableCompletedAt(t *time.Time) *InventoryUpdate {
	if t != nil {
		iu.SetCompletedAt(*t)
	}
	return iu
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (iu *InventoryUpdate) ClearCompletedAt() *InventoryUpdate {
	iu.mutation.ClearCompletedAt()
	return iu
}

// AddItemIDs adds the "items" edge to the InventoryItem entity by IDs.
func (iu *InventoryUpdate) AddItemIDs(ids ...int64) *InventoryUpdate {
	iu.mutation.AddItemIDs(ids...)
	return iu
}

// AddItems adds the "items" edges to the InventoryItem entity.
func (iu *InventoryUpdate) AddItems(i ...*InventoryItem) *InventoryUpdate {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return iu.AddItemIDs(ids...)
}

// Mutation returns the InventoryMutation object of the builder.
func (iu *InventoryUpdate) Mutation() *InventoryMutation {
	return iu.mutation
}

// ClearItems clears all "items" edges to the InventoryItem entity.
func (iu *InventoryUpdate) ClearItems() *InventoryUpdate {
	iu.mutation.ClearItems()
	return iu
}

// RemoveItemIDs removes the "items" edge to InventoryItem entities by IDs.
func (iu *InventoryUpdate) RemoveItemIDs(ids ...int64) *InventoryUpdate {
	iu.mutation.RemoveItemIDs(ids...)
	return iu
}

// RemoveItems removes "items" edges to InventoryItem entities.
func (iu *InventoryUpdate) RemoveItems(i ...*InventoryItem) *InventoryUpdate {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return iu.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *InventoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *InventoryUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *InventoryUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *InventoryUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *InventoryUpdate) check() error {
	if v, ok := iu.mutation.Status(); ok {
		if err := inventory.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Inventory.status": %w`, err)}
		}
	}
	if iu.mutation.WarehouseCleared() && len(iu.mutation.WarehouseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Inventory.warehouse"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (iu *InventoryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InventoryUpdate {
	iu.modifiers = append(iu.modifiers, modifiers...)
	return iu
}

func (iu *InventoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(inventory.Table, inventory.Columns, sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.Status(); ok {
		_spec.SetField(inventory.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := iu.mutation.CompletedAt(); ok {
		_spec.SetField(inventory.FieldCompletedAt, field.TypeTime, value)
	}
	if iu.mutation.CompletedAtCleared() {
		_spec.ClearField(inventory.FieldCompletedAt, field.TypeTime)
	}
	if iu.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.ItemsTable,
			Columns: []string{inventory.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.RemovedItemsIDs(); len(nodes) > 0 && !iu.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.ItemsTable,
			Columns: []string{inventory.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.ItemsTable,
			Columns: []string{inventory.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(iu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inventory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// InventoryUpdateOne is the builder for updating a single Inventory entity.
type InventoryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *InventoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetStatus sets the "status" field.
func (iuo *InventoryUpdateOne) SetStatus(es enum.InventoryStatus) *InventoryUpdateOne {
	iuo.mutation.SetStatus(es)
	return iuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (iuo *InventoryUpdateOne) SetNillableStatus(es *enum.InventoryStatus) *InventoryUpdateOne {
	if es != nil {
		iuo.SetStatus(*es)
	}
	return iuo
}

// SetCompletedAt sets the "completed_at" field.
func (iuo *InventoryUpdateOne) SetCompletedAt(t time.Time) *InventoryUpdateOne {
	iuo.mutation.SetCompletedAt(t)
	return iuo
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (iuo *InventoryUpdateOne) SetNillableCompletedAt(t *time.Time) *InventoryUpdateOne {
	if t != nil {
		iuo.SetCompletedAt(*t)
	}
	return iuo
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (iuo *InventoryUpdateOne) ClearCompletedAt() *InventoryUpdateOne {
	iuo.mutation.ClearCompletedAt()
	return iuo
}

// AddItemIDs adds the "items" edge to the InventoryItem entity by IDs.
func (iuo *InventoryUpdateOne) AddItemIDs(ids ...int64) *InventoryUpdateOne {
	iuo.mutation.AddItemIDs(ids...)
	return iuo
}

// AddItems adds the "items" edges to the InventoryItem entity.
func (iuo *InventoryUpdateOne) AddItems(i ...*InventoryItem) *InventoryUpdateOne {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return iuo.AddItemIDs(ids...)
}

// Mutation returns the InventoryMutation object of the builder.
func (iuo *InventoryUpdateOne) Mutation() *InventoryMutation {
	return iuo.mutation
}

// ClearItems clears all "items" edges to the InventoryItem entity.
func (iuo *InventoryUpdateOne) ClearItems() *InventoryUpdateOne {
	iuo.mutation.ClearItems()
	return iuo
}

// RemoveItemIDs removes the "items" edge to InventoryItem entities by IDs.
func (iuo *InventoryUpdateOne) RemoveItemIDs(ids ...int64) *InventoryUpdateOne {
	iuo.mutation.RemoveItemIDs(ids...)
	return iuo
}

// RemoveItems removes "items" edges to InventoryItem entities.
func (iuo *InventoryUpdateOne) RemoveItems(i ...*InventoryItem) *InventoryUpdateOne {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return iuo.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the InventoryUpdate builder.
func (iuo *InventoryUpdateOne) Where(ps ...predicate.Inventory) *InventoryUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *InventoryUpdateOne) Select(field string, fields ...string) *InventoryUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Inventory entity.
func (iuo *InventoryUpdateOne) Save(ctx context.Context) (*Inventory, error) {
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *InventoryUpdateOne) SaveX(ctx context.Context) *Inventory {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *InventoryUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *InventoryUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *InventoryUpdateOne) check() error {
	if v, ok := iuo.mutation.Status(); ok {
		if err := inventory.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Inventory.status": %w`, err)}
		}
	}
	if iuo.mutation.WarehouseCleared() && len(iuo.mutation.WarehouseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Inventory.warehouse"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (iuo *InventoryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InventoryUpdateOne {
	iuo.modifiers = append(iuo.modifiers, modifiers...)
	return iuo
}

func (iuo *InventoryUpdateOne) sqlSave(ctx context.Context) (_node *Inventory, err error) {
	if err := iuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inventory.Table, inventory.Columns, sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Inventory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inventory.FieldID)
		for _, f := range fields {
			if !inventory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != inventory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.Status(); ok {
		_spec.SetField(inventory.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := iuo.mutation.CompletedAt(); ok {
		_spec.SetField(inventory.FieldCompletedAt, field.TypeTime, value)
	}
	if iuo.mutation.CompletedAtCleared() {
		_spec.ClearField(inventory.FieldCompletedAt, field.TypeTime)
	}
	if iuo.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.ItemsTable,
			Columns: []string{inventory.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.RemovedItemsIDs(); len(nodes) > 0 && !iuo.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.ItemsTable,
			Columns: []string{inventory.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.ItemsTable,
			Columns: []string{inventory.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(iuo.modifiers...)
	_node = &Inventory{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inventory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
