// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/warehouse/ent/enum"
	"github.com/makesalekz/warehouse/ent/stockmovement"
	"github.com/makesalekz/warehouse/ent/warehouse"
)

// StockMovement is the model entity for the StockMovement schema.
type StockMovement struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// WarehouseID holds the value of the "warehouse_id" field.
	WarehouseID int64 `json:"warehouse_id,omitempty"`
	// Type holds the value of the "type" field.
	Type enum.MovementType `json:"type,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID int64 `json:"product_id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity decimal.Decimal `json:"quantity,omitempty"`
	// CounterpartyID holds the value of the "counterparty_id" field.
	CounterpartyID *int64 `json:"counterparty_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StockMovementQuery when eager-loading is set.
	Edges        StockMovementEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StockMovementEdges holds the relations/edges for other nodes in the graph.
type StockMovementEdges struct {
	// Warehouse holds the value of the warehouse edge.
	Warehouse *Warehouse `json:"warehouse,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WarehouseOrErr returns the Warehouse value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StockMovementEdges) WarehouseOrErr() (*Warehouse, error) {
	if e.Warehouse != nil {
		return e.Warehouse, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: warehouse.Label}
	}
	return nil, &NotLoadedError{edge: "warehouse"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StockMovement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stockmovement.FieldQuantity:
			values[i] = new(decimal.Decimal)
		case stockmovement.FieldID, stockmovement.FieldTenantID, stockmovement.FieldWarehouseID, stockmovement.FieldProductID, stockmovement.FieldCounterpartyID, stockmovement.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case stockmovement.FieldType, stockmovement.FieldReason:
			values[i] = new(sql.NullString)
		case stockmovement.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StockMovement fields.
func (sm *StockMovement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stockmovement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sm.ID = int64(value.Int64)
		case stockmovement.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				sm.TenantID = value.Int64
			}
		case stockmovement.FieldWarehouseID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field warehouse_id", values[i])
			} else if value.Valid {
				sm.WarehouseID = value.Int64
			}
		case stockmovement.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				sm.Type = enum.MovementType(value.String)
			}
		case stockmovement.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				sm.ProductID = value.Int64
			}
		case stockmovement.FieldQuantity:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value != nil {
				sm.Quantity = *value
			}
		case stockmovement.FieldCounterpartyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field counterparty_id", values[i])
			} else if value.Valid {
				sm.CounterpartyID = new(int64)
				*sm.CounterpartyID = value.Int64
			}
		case stockmovement.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				sm.Reason = new(string)
				*sm.Reason = value.String
			}
		case stockmovement.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				sm.CreatedBy = value.Int64
			}
		case stockmovement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sm.CreatedAt = value.Time
			}
		default:
			sm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StockMovement.
// This includes values selected through modifiers, order, etc.
func (sm *StockMovement) Value(name string) (ent.Value, error) {
	return sm.selectValues.Get(name)
}

// QueryWarehouse queries the "warehouse" edge of the StockMovement entity.
func (sm *StockMovement) QueryWarehouse() *WarehouseQuery {
	return NewStockMovementClient(sm.config).QueryWarehouse(sm)
}

// Update returns a builder for updating this StockMovement.
// Note that you need to call StockMovement.Unwrap() before calling this method if this StockMovement
// was returned from a transaction, and the transaction was committed or rolled back.
func (sm *StockMovement) Update() *StockMovementUpdateOne {
	return NewStockMovementClient(sm.config).UpdateOne(sm)
}

// Unwrap unwraps the StockMovement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sm *StockMovement) Unwrap() *StockMovement {
	_tx, ok := sm.config.driver.(*txDriver)
	if !ok {
		panic("ent: StockMovement is not a transactional entity")
	}
	sm.config.driver = _tx.drv
	return sm
}

// String implements the fmt.Stringer.
func (sm *StockMovement) String() string {
	var builder strings.Builder
	builder.WriteString("StockMovement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sm.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", sm.TenantID))
	builder.WriteString(", ")
	builder.WriteString("warehouse_id=")
	builder.WriteString(fmt.Sprintf("%v", sm.WarehouseID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", sm.Type))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", sm.ProductID))
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", sm.Quantity))
	builder.WriteString(", ")
	if v := sm.CounterpartyID; v != nil {
		builder.WriteString("counterparty_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := sm.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", sm.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sm.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StockMovements is a parsable slice of StockMovement.
type StockMovements []*StockMovement
