// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/warehouse/ent/stockitem"
	"gitlab.calendaria.team/services/warehouse/ent/warehouse"
)

// StockItemCreate is the builder for creating a StockItem entity.
type StockItemCreate struct {
	config
	mutation *StockItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (sic *StockItemCreate) SetCreatedAt(t time.Time) *StockItemCreate {
	sic.mutation.SetCreatedAt(t)
	return sic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sic *StockItemCreate) SetNillableCreatedAt(t *time.Time) *StockItemCreate {
	if t != nil {
		sic.SetCreatedAt(*t)
	}
	return sic
}

// SetUpdatedAt sets the "updated_at" field.
func (sic *StockItemCreate) SetUpdatedAt(t time.Time) *StockItemCreate {
	sic.mutation.SetUpdatedAt(t)
	return sic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sic *StockItemCreate) SetNillableUpdatedAt(t *time.Time) *StockItemCreate {
	if t != nil {
		sic.SetUpdatedAt(*t)
	}
	return sic
}

// SetTenantID sets the "tenant_id" field.
func (sic *StockItemCreate) SetTenantID(i int64) *StockItemCreate {
	sic.mutation.SetTenantID(i)
	return sic
}

// SetWarehouseID sets the "warehouse_id" field.
func (sic *StockItemCreate) SetWarehouseID(i int64) *StockItemCreate {
	sic.mutation.SetWarehouseID(i)
	return sic
}

// SetProductID sets the "product_id" field.
func (sic *StockItemCreate) SetProductID(i int64) *StockItemCreate {
	sic.mutation.SetProductID(i)
	return sic
}

// SetQuantity sets the "quantity" field.
func (sic *StockItemCreate) SetQuantity(d decimal.Decimal) *StockItemCreate {
	sic.mutation.SetQuantity(d)
	return sic
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (sic *StockItemCreate) SetNillableQuantity(d *decimal.Decimal) *StockItemCreate {
	if d != nil {
		sic.SetQuantity(*d)
	}
	return sic
}

// SetMinQuantity sets the "min_quantity" field.
func (sic *StockItemCreate) SetMinQuantity(d decimal.Decimal) *StockItemCreate {
	sic.mutation.SetMinQuantity(d)
	return sic
}

// SetNillableMinQuantity sets the "min_quantity" field if the given value is not nil.
func (sic *StockItemCreate) SetNillableMinQuantity(d *decimal.Decimal) *StockItemCreate {
	if d != nil {
		sic.SetMinQuantity(*d)
	}
	return sic
}

// SetID sets the "id" field.
func (sic *StockItemCreate) SetID(i int64) *StockItemCreate {
	sic.mutation.SetID(i)
	return sic
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (sic *StockItemCreate) SetWarehouse(w *Warehouse) *StockItemCreate {
	return sic.SetWarehouseID(w.ID)
}

// Mutation returns the StockItemMutation object of the builder.
func (sic *StockItemCreate) Mutation() *StockItemMutation {
	return sic.mutation
}

// Save creates the StockItem in the database.
func (sic *StockItemCreate) Save(ctx context.Context) (*StockItem, error) {
	sic.defaults()
	return withHooks(ctx, sic.sqlSave, sic.mutation, sic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sic *StockItemCreate) SaveX(ctx context.Context) *StockItem {
	v, err := sic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sic *StockItemCreate) Exec(ctx context.Context) error {
	_, err := sic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sic *StockItemCreate) ExecX(ctx context.Context) {
	if err := sic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sic *StockItemCreate) defaults() {
	if _, ok := sic.mutation.CreatedAt(); !ok {
		v := stockitem.DefaultCreatedAt()
		sic.mutation.SetCreatedAt(v)
	}
	if _, ok := sic.mutation.UpdatedAt(); !ok {
		v := stockitem.DefaultUpdatedAt()
		sic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sic *StockItemCreate) check() error {
	if _, ok := sic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StockItem.created_at"`)}
	}
	if _, ok := sic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StockItem.updated_at"`)}
	}
	if _, ok := sic.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "StockItem.tenant_id"`)}
	}
	if _, ok := sic.mutation.WarehouseID(); !ok {
		return &ValidationError{Name: "warehouse_id", err: errors.New(`ent: missing required field "StockItem.warehouse_id"`)}
	}
	if _, ok := sic.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "StockItem.product_id"`)}
	}
	if len(sic.mutation.WarehouseIDs()) == 0 {
		return &ValidationError{Name: "warehouse", err: errors.New(`ent: missing required edge "StockItem.warehouse"`)}
	}
	return nil
}

func (sic *StockItemCreate) sqlSave(ctx context.Context) (*StockItem, error) {
	if err := sic.check(); err != nil {
		return nil, err
	}
	_node, _spec := sic.createSpec()
	if err := sqlgraph.CreateNode(ctx, sic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sic.mutation.id = &_node.ID
	sic.mutation.done = true
	return _node, nil
}

func (sic *StockItemCreate) createSpec() (*StockItem, *sqlgraph.CreateSpec) {
	var (
		_node = &StockItem{config: sic.config}
		_spec = sqlgraph.NewCreateSpec(stockitem.Table, sqlgraph.NewFieldSpec(stockitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = sic.conflict
	if id, ok := sic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sic.mutation.CreatedAt(); ok {
		_spec.SetField(stockitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sic.mutation.UpdatedAt(); ok {
		_spec.SetField(stockitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sic.mutation.TenantID(); ok {
		_spec.SetField(stockitem.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := sic.mutation.ProductID(); ok {
		_spec.SetField(stockitem.FieldProductID, field.TypeInt64, value)
		_node.ProductID = value
	}
	if value, ok := sic.mutation.Quantity(); ok {
		_spec.SetField(stockitem.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := sic.mutation.MinQuantity(); ok {
		_spec.SetField(stockitem.FieldMinQuantity, field.TypeFloat64, value)
		_node.MinQuantity = value
	}
	if nodes := sic.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stockitem.WarehouseTable,
			Columns: []string{stockitem.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WarehouseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StockItem.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StockItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (sic *StockItemCreate) OnConflict(opts ...sql.ConflictOption) *StockItemUpsertOne {
	sic.conflict = opts
	return &StockItemUpsertOne{
		create: sic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StockItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sic *StockItemCreate) OnConflictColumns(columns ...string) *StockItemUpsertOne {
	sic.conflict = append(sic.conflict, sql.ConflictColumns(columns...))
	return &StockItemUpsertOne{
		create: sic,
	}
}

type (
	// StockItemUpsertOne is the builder for "upsert"-ing
	//  one StockItem node.
	StockItemUpsertOne struct {
		create *StockItemCreate
	}

	// StockItemUpsert is the "OnConflict" setter.
	StockItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *StockItemUpsert) SetUpdatedAt(v time.Time) *StockItemUpsert {
	u.Set(stockitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StockItemUpsert) UpdateUpdatedAt() *StockItemUpsert {
	u.SetExcluded(stockitem.FieldUpdatedAt)
	return u
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *StockItemUpsert) SetWarehouseID(v int64) *StockItemUpsert {
	u.Set(stockitem.FieldWarehouseID, v)
	return u
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *StockItemUpsert) UpdateWarehouseID() *StockItemUpsert {
	u.SetExcluded(stockitem.FieldWarehouseID)
	return u
}

// SetProductID sets the "product_id" field.
func (u *StockItemUpsert) SetProductID(v int64) *StockItemUpsert {
	u.Set(stockitem.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *StockItemUpsert) UpdateProductID() *StockItemUpsert {
	u.SetExcluded(stockitem.FieldProductID)
	return u
}

// AddProductID adds v to the "product_id" field.
func (u *StockItemUpsert) AddProductID(v int64) *StockItemUpsert {
	u.Add(stockitem.FieldProductID, v)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *StockItemUpsert) SetQuantity(v decimal.Decimal) *StockItemUpsert {
	u.Set(stockitem.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *StockItemUpsert) UpdateQuantity() *StockItemUpsert {
	u.SetExcluded(stockitem.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *StockItemUpsert) AddQuantity(v decimal.Decimal) *StockItemUpsert {
	u.Add(stockitem.FieldQuantity, v)
	return u
}

// ClearQuantity clears the value of the "quantity" field.
func (u *StockItemUpsert) ClearQuantity() *StockItemUpsert {
	u.SetNull(stockitem.FieldQuantity)
	return u
}

// SetMinQuantity sets the "min_quantity" field.
func (u *StockItemUpsert) SetMinQuantity(v decimal.Decimal) *StockItemUpsert {
	u.Set(stockitem.FieldMinQuantity, v)
	return u
}

// UpdateMinQuantity sets the "min_quantity" field to the value that was provided on create.
func (u *StockItemUpsert) UpdateMinQuantity() *StockItemUpsert {
	u.SetExcluded(stockitem.FieldMinQuantity)
	return u
}

// AddMinQuantity adds v to the "min_quantity" field.
func (u *StockItemUpsert) AddMinQuantity(v decimal.Decimal) *StockItemUpsert {
	u.Add(stockitem.FieldMinQuantity, v)
	return u
}

// ClearMinQuantity clears the value of the "min_quantity" field.
func (u *StockItemUpsert) ClearMinQuantity() *StockItemUpsert {
	u.SetNull(stockitem.FieldMinQuantity)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.StockItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(stockitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StockItemUpsertOne) UpdateNewValues() *StockItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(stockitem.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(stockitem.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(stockitem.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StockItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StockItemUpsertOne) Ignore() *StockItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StockItemUpsertOne) DoNothing() *StockItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StockItemCreate.OnConflict
// documentation for more info.
func (u *StockItemUpsertOne) Update(set func(*StockItemUpsert)) *StockItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StockItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StockItemUpsertOne) SetUpdatedAt(v time.Time) *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StockItemUpsertOne) UpdateUpdatedAt() *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *StockItemUpsertOne) SetWarehouseID(v int64) *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.SetWarehouseID(v)
	})
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *StockItemUpsertOne) UpdateWarehouseID() *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.UpdateWarehouseID()
	})
}

// SetProductID sets the "product_id" field.
func (u *StockItemUpsertOne) SetProductID(v int64) *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.SetProductID(v)
	})
}

// AddProductID adds v to the "product_id" field.
func (u *StockItemUpsertOne) AddProductID(v int64) *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.AddProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *StockItemUpsertOne) UpdateProductID() *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.UpdateProductID()
	})
}

// SetQuantity sets the "quantity" field.
func (u *StockItemUpsertOne) SetQuantity(v decimal.Decimal) *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *StockItemUpsertOne) AddQuantity(v decimal.Decimal) *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *StockItemUpsertOne) UpdateQuantity() *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.UpdateQuantity()
	})
}

// ClearQuantity clears the value of the "quantity" field.
func (u *StockItemUpsertOne) ClearQuantity() *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.ClearQuantity()
	})
}

// SetMinQuantity sets the "min_quantity" field.
func (u *StockItemUpsertOne) SetMinQuantity(v decimal.Decimal) *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.SetMinQuantity(v)
	})
}

// AddMinQuantity adds v to the "min_quantity" field.
func (u *StockItemUpsertOne) AddMinQuantity(v decimal.Decimal) *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.AddMinQuantity(v)
	})
}

// UpdateMinQuantity sets the "min_quantity" field to the value that was provided on create.
func (u *StockItemUpsertOne) UpdateMinQuantity() *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.UpdateMinQuantity()
	})
}

// ClearMinQuantity clears the value of the "min_quantity" field.
func (u *StockItemUpsertOne) ClearMinQuantity() *StockItemUpsertOne {
	return u.Update(func(s *StockItemUpsert) {
		s.ClearMinQuantity()
	})
}

// Exec executes the query.
func (u *StockItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StockItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StockItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StockItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StockItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StockItemCreateBulk is the builder for creating many StockItem entities in bulk.
type StockItemCreateBulk struct {
	config
	err      error
	builders []*StockItemCreate
	conflict []sql.ConflictOption
}

// Save creates the StockItem entities in the database.
func (sicb *StockItemCreateBulk) Save(ctx context.Context) ([]*StockItem, error) {
	if sicb.err != nil {
		return nil, sicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sicb.builders))
	nodes := make([]*StockItem, len(sicb.builders))
	mutators := make([]Mutator, len(sicb.builders))
	for i := range sicb.builders {
		func(i int, root context.Context) {
			builder := sicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StockItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = sicb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sicb *StockItemCreateBulk) SaveX(ctx context.Context) []*StockItem {
	v, err := sicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sicb *StockItemCreateBulk) Exec(ctx context.Context) error {
	_, err := sicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sicb *StockItemCreateBulk) ExecX(ctx context.Context) {
	if err := sicb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StockItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StockItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (sicb *StockItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *StockItemUpsertBulk {
	sicb.conflict = opts
	return &StockItemUpsertBulk{
		create: sicb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StockItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sicb *StockItemCreateBulk) OnConflictColumns(columns ...string) *StockItemUpsertBulk {
	sicb.conflict = append(sicb.conflict, sql.ConflictColumns(columns...))
	return &StockItemUpsertBulk{
		create: sicb,
	}
}

// StockItemUpsertBulk is the builder for "upsert"-ing
// a bulk of StockItem nodes.
type StockItemUpsertBulk struct {
	create *StockItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.StockItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(stockitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StockItemUpsertBulk) UpdateNewValues() *StockItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(stockitem.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(stockitem.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(stockitem.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StockItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StockItemUpsertBulk) Ignore() *StockItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StockItemUpsertBulk) DoNothing() *StockItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StockItemCreateBulk.OnConflict
// documentation for more info.
func (u *StockItemUpsertBulk) Update(set func(*StockItemUpsert)) *StockItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StockItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StockItemUpsertBulk) SetUpdatedAt(v time.Time) *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StockItemUpsertBulk) UpdateUpdatedAt() *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *StockItemUpsertBulk) SetWarehouseID(v int64) *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.SetWarehouseID(v)
	})
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *StockItemUpsertBulk) UpdateWarehouseID() *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.UpdateWarehouseID()
	})
}

// SetProductID sets the "product_id" field.
func (u *StockItemUpsertBulk) SetProductID(v int64) *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.SetProductID(v)
	})
}

// AddProductID adds v to the "product_id" field.
func (u *StockItemUpsertBulk) AddProductID(v int64) *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.AddProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *StockItemUpsertBulk) UpdateProductID() *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.UpdateProductID()
	})
}

// SetQuantity sets the "quantity" field.
func (u *StockItemUpsertBulk) SetQuantity(v decimal.Decimal) *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *StockItemUpsertBulk) AddQuantity(v decimal.Decimal) *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *StockItemUpsertBulk) UpdateQuantity() *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.UpdateQuantity()
	})
}

// ClearQuantity clears the value of the "quantity" field.
func (u *StockItemUpsertBulk) ClearQuantity() *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.ClearQuantity()
	})
}

// SetMinQuantity sets the "min_quantity" field.
func (u *StockItemUpsertBulk) SetMinQuantity(v decimal.Decimal) *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.SetMinQuantity(v)
	})
}

// AddMinQuantity adds v to the "min_quantity" field.
func (u *StockItemUpsertBulk) AddMinQuantity(v decimal.Decimal) *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.AddMinQuantity(v)
	})
}

// UpdateMinQuantity sets the "min_quantity" field to the value that was provided on create.
func (u *StockItemUpsertBulk) UpdateMinQuantity() *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.UpdateMinQuantity()
	})
}

// ClearMinQuantity clears the value of the "min_quantity" field.
func (u *StockItemUpsertBulk) ClearMinQuantity() *StockItemUpsertBulk {
	return u.Update(func(s *StockItemUpsert) {
		s.ClearMinQuantity()
	})
}

// Exec executes the query.
func (u *StockItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StockItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StockItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StockItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
