// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/warehouse/ent/enum"
	"github.com/makesalekz/warehouse/ent/stockmovement"
	"github.com/makesalekz/warehouse/ent/warehouse"
)

// StockMovementCreate is the builder for creating a StockMovement entity.
type StockMovementCreate struct {
	config
	mutation *StockMovementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (smc *StockMovementCreate) SetTenantID(i int64) *StockMovementCreate {
	smc.mutation.SetTenantID(i)
	return smc
}

// SetWarehouseID sets the "warehouse_id" field.
func (smc *StockMovementCreate) SetWarehouseID(i int64) *StockMovementCreate {
	smc.mutation.SetWarehouseID(i)
	return smc
}

// SetType sets the "type" field.
func (smc *StockMovementCreate) SetType(et enum.MovementType) *StockMovementCreate {
	smc.mutation.SetType(et)
	return smc
}

// SetProductID sets the "product_id" field.
func (smc *StockMovementCreate) SetProductID(i int64) *StockMovementCreate {
	smc.mutation.SetProductID(i)
	return smc
}

// SetQuantity sets the "quantity" field.
func (smc *StockMovementCreate) SetQuantity(d decimal.Decimal) *StockMovementCreate {
	smc.mutation.SetQuantity(d)
	return smc
}

// SetCounterpartyID sets the "counterparty_id" field.
func (smc *StockMovementCreate) SetCounterpartyID(i int64) *StockMovementCreate {
	smc.mutation.SetCounterpartyID(i)
	return smc
}

// SetNillableCounterpartyID sets the "counterparty_id" field if the given value is not nil.
func (smc *StockMovementCreate) SetNillableCounterpartyID(i *int64) *StockMovementCreate {
	if i != nil {
		smc.SetCounterpartyID(*i)
	}
	return smc
}

// SetReason sets the "reason" field.
func (smc *StockMovementCreate) SetReason(s string) *StockMovementCreate {
	smc.mutation.SetReason(s)
	return smc
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (smc *StockMovementCreate) SetNillableReason(s *string) *StockMovementCreate {
	if s != nil {
		smc.SetReason(*s)
	}
	return smc
}

// SetCreatedBy sets the "created_by" field.
func (smc *StockMovementCreate) SetCreatedBy(i int64) *StockMovementCreate {
	smc.mutation.SetCreatedBy(i)
	return smc
}

// SetCreatedAt sets the "created_at" field.
func (smc *StockMovementCreate) SetCreatedAt(t time.Time) *StockMovementCreate {
	smc.mutation.SetCreatedAt(t)
	return smc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (smc *StockMovementCreate) SetNillableCreatedAt(t *time.Time) *StockMovementCreate {
	if t != nil {
		smc.SetCreatedAt(*t)
	}
	return smc
}

// SetID sets the "id" field.
func (smc *StockMovementCreate) SetID(i int64) *StockMovementCreate {
	smc.mutation.SetID(i)
	return smc
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (smc *StockMovementCreate) SetWarehouse(w *Warehouse) *StockMovementCreate {
	return smc.SetWarehouseID(w.ID)
}

// Mutation returns the StockMovementMutation object of the builder.
func (smc *StockMovementCreate) Mutation() *StockMovementMutation {
	return smc.mutation
}

// Save creates the StockMovement in the database.
func (smc *StockMovementCreate) Save(ctx context.Context) (*StockMovement, error) {
	smc.defaults()
	return withHooks(ctx, smc.sqlSave, smc.mutation, smc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (smc *StockMovementCreate) SaveX(ctx context.Context) *StockMovement {
	v, err := smc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (smc *StockMovementCreate) Exec(ctx context.Context) error {
	_, err := smc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (smc *StockMovementCreate) ExecX(ctx context.Context) {
	if err := smc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (smc *StockMovementCreate) defaults() {
	if _, ok := smc.mutation.CreatedAt(); !ok {
		v := stockmovement.DefaultCreatedAt()
		smc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (smc *StockMovementCreate) check() error {
	if _, ok := smc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "StockMovement.tenant_id"`)}
	}
	if _, ok := smc.mutation.WarehouseID(); !ok {
		return &ValidationError{Name: "warehouse_id", err: errors.New(`ent: missing required field "StockMovement.warehouse_id"`)}
	}
	if _, ok := smc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "StockMovement.type"`)}
	}
	if v, ok := smc.mutation.GetType(); ok {
		if err := stockmovement.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "StockMovement.type": %w`, err)}
		}
	}
	if _, ok := smc.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "StockMovement.product_id"`)}
	}
	if _, ok := smc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "StockMovement.quantity"`)}
	}
	if _, ok := smc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "StockMovement.created_by"`)}
	}
	if _, ok := smc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StockMovement.created_at"`)}
	}
	if len(smc.mutation.WarehouseIDs()) == 0 {
		return &ValidationError{Name: "warehouse", err: errors.New(`ent: missing required edge "StockMovement.warehouse"`)}
	}
	return nil
}

func (smc *StockMovementCreate) sqlSave(ctx context.Context) (*StockMovement, error) {
	if err := smc.check(); err != nil {
		return nil, err
	}
	_node, _spec := smc.createSpec()
	if err := sqlgraph.CreateNode(ctx, smc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	smc.mutation.id = &_node.ID
	smc.mutation.done = true
	return _node, nil
}

func (smc *StockMovementCreate) createSpec() (*StockMovement, *sqlgraph.CreateSpec) {
	var (
		_node = &StockMovement{config: smc.config}
		_spec = sqlgraph.NewCreateSpec(stockmovement.Table, sqlgraph.NewFieldSpec(stockmovement.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = smc.conflict
	if id, ok := smc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := smc.mutation.TenantID(); ok {
		_spec.SetField(stockmovement.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := smc.mutation.GetType(); ok {
		_spec.SetField(stockmovement.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := smc.mutation.ProductID(); ok {
		_spec.SetField(stockmovement.FieldProductID, field.TypeInt64, value)
		_node.ProductID = value
	}
	if value, ok := smc.mutation.Quantity(); ok {
		_spec.SetField(stockmovement.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := smc.mutation.CounterpartyID(); ok {
		_spec.SetField(stockmovement.FieldCounterpartyID, field.TypeInt64, value)
		_node.CounterpartyID = &value
	}
	if value, ok := smc.mutation.Reason(); ok {
		_spec.SetField(stockmovement.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := smc.mutation.CreatedBy(); ok {
		_spec.SetField(stockmovement.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := smc.mutation.CreatedAt(); ok {
		_spec.SetField(stockmovement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := smc.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stockmovement.WarehouseTable,
			Columns: []string{stockmovement.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WarehouseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StockMovement.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StockMovementUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (smc *StockMovementCreate) OnConflict(opts ...sql.ConflictOption) *StockMovementUpsertOne {
	smc.conflict = opts
	return &StockMovementUpsertOne{
		create: smc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StockMovement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (smc *StockMovementCreate) OnConflictColumns(columns ...string) *StockMovementUpsertOne {
	smc.conflict = append(smc.conflict, sql.ConflictColumns(columns...))
	return &StockMovementUpsertOne{
		create: smc,
	}
}

type (
	// StockMovementUpsertOne is the builder for "upsert"-ing
	//  one StockMovement node.
	StockMovementUpsertOne struct {
		create *StockMovementCreate
	}

	// StockMovementUpsert is the "OnConflict" setter.
	StockMovementUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.StockMovement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(stockmovement.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StockMovementUpsertOne) UpdateNewValues() *StockMovementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(stockmovement.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(stockmovement.FieldTenantID)
		}
		if _, exists := u.create.mutation.WarehouseID(); exists {
			s.SetIgnore(stockmovement.FieldWarehouseID)
		}
		if _, exists := u.create.mutation.GetType(); exists {
			s.SetIgnore(stockmovement.FieldType)
		}
		if _, exists := u.create.mutation.ProductID(); exists {
			s.SetIgnore(stockmovement.FieldProductID)
		}
		if _, exists := u.create.mutation.Quantity(); exists {
			s.SetIgnore(stockmovement.FieldQuantity)
		}
		if _, exists := u.create.mutation.CounterpartyID(); exists {
			s.SetIgnore(stockmovement.FieldCounterpartyID)
		}
		if _, exists := u.create.mutation.Reason(); exists {
			s.SetIgnore(stockmovement.FieldReason)
		}
		if _, exists := u.create.mutation.CreatedBy(); exists {
			s.SetIgnore(stockmovement.FieldCreatedBy)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(stockmovement.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StockMovement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StockMovementUpsertOne) Ignore() *StockMovementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StockMovementUpsertOne) DoNothing() *StockMovementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StockMovementCreate.OnConflict
// documentation for more info.
func (u *StockMovementUpsertOne) Update(set func(*StockMovementUpsert)) *StockMovementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StockMovementUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *StockMovementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StockMovementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StockMovementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StockMovementUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StockMovementUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StockMovementCreateBulk is the builder for creating many StockMovement entities in bulk.
type StockMovementCreateBulk struct {
	config
	err      error
	builders []*StockMovementCreate
	conflict []sql.ConflictOption
}

// Save creates the StockMovement entities in the database.
func (smcb *StockMovementCreateBulk) Save(ctx context.Context) ([]*StockMovement, error) {
	if smcb.err != nil {
		return nil, smcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(smcb.builders))
	nodes := make([]*StockMovement, len(smcb.builders))
	mutators := make([]Mutator, len(smcb.builders))
	for i := range smcb.builders {
		func(i int, root context.Context) {
			builder := smcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StockMovementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, smcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = smcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, smcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, smcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (smcb *StockMovementCreateBulk) SaveX(ctx context.Context) []*StockMovement {
	v, err := smcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (smcb *StockMovementCreateBulk) Exec(ctx context.Context) error {
	_, err := smcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (smcb *StockMovementCreateBulk) ExecX(ctx context.Context) {
	if err := smcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StockMovement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StockMovementUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (smcb *StockMovementCreateBulk) OnConflict(opts ...sql.ConflictOption) *StockMovementUpsertBulk {
	smcb.conflict = opts
	return &StockMovementUpsertBulk{
		create: smcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StockMovement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (smcb *StockMovementCreateBulk) OnConflictColumns(columns ...string) *StockMovementUpsertBulk {
	smcb.conflict = append(smcb.conflict, sql.ConflictColumns(columns...))
	return &StockMovementUpsertBulk{
		create: smcb,
	}
}

// StockMovementUpsertBulk is the builder for "upsert"-ing
// a bulk of StockMovement nodes.
type StockMovementUpsertBulk struct {
	create *StockMovementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.StockMovement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(stockmovement.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StockMovementUpsertBulk) UpdateNewValues() *StockMovementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(stockmovement.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(stockmovement.FieldTenantID)
			}
			if _, exists := b.mutation.WarehouseID(); exists {
				s.SetIgnore(stockmovement.FieldWarehouseID)
			}
			if _, exists := b.mutation.GetType(); exists {
				s.SetIgnore(stockmovement.FieldType)
			}
			if _, exists := b.mutation.ProductID(); exists {
				s.SetIgnore(stockmovement.FieldProductID)
			}
			if _, exists := b.mutation.Quantity(); exists {
				s.SetIgnore(stockmovement.FieldQuantity)
			}
			if _, exists := b.mutation.CounterpartyID(); exists {
				s.SetIgnore(stockmovement.FieldCounterpartyID)
			}
			if _, exists := b.mutation.Reason(); exists {
				s.SetIgnore(stockmovement.FieldReason)
			}
			if _, exists := b.mutation.CreatedBy(); exists {
				s.SetIgnore(stockmovement.FieldCreatedBy)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(stockmovement.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StockMovement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StockMovementUpsertBulk) Ignore() *StockMovementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StockMovementUpsertBulk) DoNothing() *StockMovementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StockMovementCreateBulk.OnConflict
// documentation for more info.
func (u *StockMovementUpsertBulk) Update(set func(*StockMovementUpsert)) *StockMovementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StockMovementUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *StockMovementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StockMovementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StockMovementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StockMovementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
