// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/warehouse/ent/predicate"
	"gitlab.calendaria.team/services/warehouse/ent/stockmovement"
	"gitlab.calendaria.team/services/warehouse/ent/warehouse"
)

// StockMovementQuery is the builder for querying StockMovement entities.
type StockMovementQuery struct {
	config
	ctx           *QueryContext
	order         []stockmovement.OrderOption
	inters        []Interceptor
	predicates    []predicate.StockMovement
	withWarehouse *WarehouseQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StockMovementQuery builder.
func (smq *StockMovementQuery) Where(ps ...predicate.StockMovement) *StockMovementQuery {
	smq.predicates = append(smq.predicates, ps...)
	return smq
}

// Limit the number of records to be returned by this query.
func (smq *StockMovementQuery) Limit(limit int) *StockMovementQuery {
	smq.ctx.Limit = &limit
	return smq
}

// Offset to start from.
func (smq *StockMovementQuery) Offset(offset int) *StockMovementQuery {
	smq.ctx.Offset = &offset
	return smq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (smq *StockMovementQuery) Unique(unique bool) *StockMovementQuery {
	smq.ctx.Unique = &unique
	return smq
}

// Order specifies how the records should be ordered.
func (smq *StockMovementQuery) Order(o ...stockmovement.OrderOption) *StockMovementQuery {
	smq.order = append(smq.order, o...)
	return smq
}

// QueryWarehouse chains the current query on the "warehouse" edge.
func (smq *StockMovementQuery) QueryWarehouse() *WarehouseQuery {
	query := (&WarehouseClient{config: smq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := smq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := smq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stockmovement.Table, stockmovement.FieldID, selector),
			sqlgraph.To(warehouse.Table, warehouse.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stockmovement.WarehouseTable, stockmovement.WarehouseColumn),
		)
		fromU = sqlgraph.SetNeighbors(smq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StockMovement entity from the query.
// Returns a *NotFoundError when no StockMovement was found.
func (smq *StockMovementQuery) First(ctx context.Context) (*StockMovement, error) {
	nodes, err := smq.Limit(1).All(setContextOp(ctx, smq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stockmovement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (smq *StockMovementQuery) FirstX(ctx context.Context) *StockMovement {
	node, err := smq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StockMovement ID from the query.
// Returns a *NotFoundError when no StockMovement ID was found.
func (smq *StockMovementQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = smq.Limit(1).IDs(setContextOp(ctx, smq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stockmovement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (smq *StockMovementQuery) FirstIDX(ctx context.Context) int64 {
	id, err := smq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StockMovement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StockMovement entity is found.
// Returns a *NotFoundError when no StockMovement entities are found.
func (smq *StockMovementQuery) Only(ctx context.Context) (*StockMovement, error) {
	nodes, err := smq.Limit(2).All(setContextOp(ctx, smq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stockmovement.Label}
	default:
		return nil, &NotSingularError{stockmovement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (smq *StockMovementQuery) OnlyX(ctx context.Context) *StockMovement {
	node, err := smq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StockMovement ID in the query.
// Returns a *NotSingularError when more than one StockMovement ID is found.
// Returns a *NotFoundError when no entities are found.
func (smq *StockMovementQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = smq.Limit(2).IDs(setContextOp(ctx, smq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stockmovement.Label}
	default:
		err = &NotSingularError{stockmovement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (smq *StockMovementQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := smq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StockMovements.
func (smq *StockMovementQuery) All(ctx context.Context) ([]*StockMovement, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryAll)
	if err := smq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StockMovement, *StockMovementQuery]()
	return withInterceptors[[]*StockMovement](ctx, smq, qr, smq.inters)
}

// AllX is like All, but panics if an error occurs.
func (smq *StockMovementQuery) AllX(ctx context.Context) []*StockMovement {
	nodes, err := smq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StockMovement IDs.
func (smq *StockMovementQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if smq.ctx.Unique == nil && smq.path != nil {
		smq.Unique(true)
	}
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryIDs)
	if err = smq.Select(stockmovement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (smq *StockMovementQuery) IDsX(ctx context.Context) []int64 {
	ids, err := smq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (smq *StockMovementQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryCount)
	if err := smq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, smq, querierCount[*StockMovementQuery](), smq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (smq *StockMovementQuery) CountX(ctx context.Context) int {
	count, err := smq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (smq *StockMovementQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryExist)
	switch _, err := smq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (smq *StockMovementQuery) ExistX(ctx context.Context) bool {
	exist, err := smq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StockMovementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (smq *StockMovementQuery) Clone() *StockMovementQuery {
	if smq == nil {
		return nil
	}
	return &StockMovementQuery{
		config:        smq.config,
		ctx:           smq.ctx.Clone(),
		order:         append([]stockmovement.OrderOption{}, smq.order...),
		inters:        append([]Interceptor{}, smq.inters...),
		predicates:    append([]predicate.StockMovement{}, smq.predicates...),
		withWarehouse: smq.withWarehouse.Clone(),
		// clone intermediate query.
		sql:  smq.sql.Clone(),
		path: smq.path,
	}
}

// WithWarehouse tells the query-builder to eager-load the nodes that are connected to
// the "warehouse" edge. The optional arguments are used to configure the query builder of the edge.
func (smq *StockMovementQuery) WithWarehouse(opts ...func(*WarehouseQuery)) *StockMovementQuery {
	query := (&WarehouseClient{config: smq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	smq.withWarehouse = query
	return smq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID int64 `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StockMovement.Query().
//		GroupBy(stockmovement.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (smq *StockMovementQuery) GroupBy(field string, fields ...string) *StockMovementGroupBy {
	smq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StockMovementGroupBy{build: smq}
	grbuild.flds = &smq.ctx.Fields
	grbuild.label = stockmovement.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID int64 `json:"tenant_id,omitempty"`
//	}
//
//	client.StockMovement.Query().
//		Select(stockmovement.FieldTenantID).
//		Scan(ctx, &v)
func (smq *StockMovementQuery) Select(fields ...string) *StockMovementSelect {
	smq.ctx.Fields = append(smq.ctx.Fields, fields...)
	sbuild := &StockMovementSelect{StockMovementQuery: smq}
	sbuild.label = stockmovement.Label
	sbuild.flds, sbuild.scan = &smq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StockMovementSelect configured with the given aggregations.
func (smq *StockMovementQuery) Aggregate(fns ...AggregateFunc) *StockMovementSelect {
	return smq.Select().Aggregate(fns...)
}

func (smq *StockMovementQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range smq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, smq); err != nil {
				return err
			}
		}
	}
	for _, f := range smq.ctx.Fields {
		if !stockmovement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if smq.path != nil {
		prev, err := smq.path(ctx)
		if err != nil {
			return err
		}
		smq.sql = prev
	}
	return nil
}

func (smq *StockMovementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StockMovement, error) {
	var (
		nodes       = []*StockMovement{}
		_spec       = smq.querySpec()
		loadedTypes = [1]bool{
			smq.withWarehouse != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StockMovement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StockMovement{config: smq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(smq.modifiers) > 0 {
		_spec.Modifiers = smq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, smq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := smq.withWarehouse; query != nil {
		if err := smq.loadWarehouse(ctx, query, nodes, nil,
			func(n *StockMovement, e *Warehouse) { n.Edges.Warehouse = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (smq *StockMovementQuery) loadWarehouse(ctx context.Context, query *WarehouseQuery, nodes []*StockMovement, init func(*StockMovement), assign func(*StockMovement, *Warehouse)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*StockMovement)
	for i := range nodes {
		fk := nodes[i].WarehouseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(warehouse.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "warehouse_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (smq *StockMovementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := smq.querySpec()
	if len(smq.modifiers) > 0 {
		_spec.Modifiers = smq.modifiers
	}
	_spec.Node.Columns = smq.ctx.Fields
	if len(smq.ctx.Fields) > 0 {
		_spec.Unique = smq.ctx.Unique != nil && *smq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, smq.driver, _spec)
}

func (smq *StockMovementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stockmovement.Table, stockmovement.Columns, sqlgraph.NewFieldSpec(stockmovement.FieldID, field.TypeInt64))
	_spec.From = smq.sql
	if unique := smq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if smq.path != nil {
		_spec.Unique = true
	}
	if fields := smq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stockmovement.FieldID)
		for i := range fields {
			if fields[i] != stockmovement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if smq.withWarehouse != nil {
			_spec.Node.AddColumnOnce(stockmovement.FieldWarehouseID)
		}
	}
	if ps := smq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := smq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := smq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := smq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (smq *StockMovementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(smq.driver.Dialect())
	t1 := builder.Table(stockmovement.Table)
	columns := smq.ctx.Fields
	if len(columns) == 0 {
		columns = stockmovement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if smq.sql != nil {
		selector = smq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if smq.ctx.Unique != nil && *smq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range smq.modifiers {
		m(selector)
	}
	for _, p := range smq.predicates {
		p(selector)
	}
	for _, p := range smq.order {
		p(selector)
	}
	if offset := smq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := smq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (smq *StockMovementQuery) Modify(modifiers ...func(s *sql.Selector)) *StockMovementSelect {
	smq.modifiers = append(smq.modifiers, modifiers...)
	return smq.Select()
}

// StockMovementGroupBy is the group-by builder for StockMovement entities.
type StockMovementGroupBy struct {
	selector
	build *StockMovementQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (smgb *StockMovementGroupBy) Aggregate(fns ...AggregateFunc) *StockMovementGroupBy {
	smgb.fns = append(smgb.fns, fns...)
	return smgb
}

// Scan applies the selector query and scans the result into the given value.
func (smgb *StockMovementGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, smgb.build.ctx, ent.OpQueryGroupBy)
	if err := smgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockMovementQuery, *StockMovementGroupBy](ctx, smgb.build, smgb, smgb.build.inters, v)
}

func (smgb *StockMovementGroupBy) sqlScan(ctx context.Context, root *StockMovementQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(smgb.fns))
	for _, fn := range smgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*smgb.flds)+len(smgb.fns))
		for _, f := range *smgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*smgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := smgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StockMovementSelect is the builder for selecting fields of StockMovement entities.
type StockMovementSelect struct {
	*StockMovementQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sms *StockMovementSelect) Aggregate(fns ...AggregateFunc) *StockMovementSelect {
	sms.fns = append(sms.fns, fns...)
	return sms
}

// Scan applies the selector query and scans the result into the given value.
func (sms *StockMovementSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sms.ctx, ent.OpQuerySelect)
	if err := sms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockMovementQuery, *StockMovementSelect](ctx, sms.StockMovementQuery, sms, sms.inters, v)
}

func (sms *StockMovementSelect) sqlScan(ctx context.Context, root *StockMovementQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sms.fns))
	for _, fn := range sms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sms *StockMovementSelect) Modify(modifiers ...func(s *sql.Selector)) *StockMovementSelect {
	sms.modifiers = append(sms.modifiers, modifiers...)
	return sms
}
