// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/warehouse/ent/predicate"
	"github.com/makesalekz/warehouse/ent/stockitem"
	"github.com/makesalekz/warehouse/ent/warehouse"
)

// StockItemQuery is the builder for querying StockItem entities.
type StockItemQuery struct {
	config
	ctx           *QueryContext
	order         []stockitem.OrderOption
	inters        []Interceptor
	predicates    []predicate.StockItem
	withWarehouse *WarehouseQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StockItemQuery builder.
func (siq *StockItemQuery) Where(ps ...predicate.StockItem) *StockItemQuery {
	siq.predicates = append(siq.predicates, ps...)
	return siq
}

// Limit the number of records to be returned by this query.
func (siq *StockItemQuery) Limit(limit int) *StockItemQuery {
	siq.ctx.Limit = &limit
	return siq
}

// Offset to start from.
func (siq *StockItemQuery) Offset(offset int) *StockItemQuery {
	siq.ctx.Offset = &offset
	return siq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (siq *StockItemQuery) Unique(unique bool) *StockItemQuery {
	siq.ctx.Unique = &unique
	return siq
}

// Order specifies how the records should be ordered.
func (siq *StockItemQuery) Order(o ...stockitem.OrderOption) *StockItemQuery {
	siq.order = append(siq.order, o...)
	return siq
}

// QueryWarehouse chains the current query on the "warehouse" edge.
func (siq *StockItemQuery) QueryWarehouse() *WarehouseQuery {
	query := (&WarehouseClient{config: siq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := siq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := siq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stockitem.Table, stockitem.FieldID, selector),
			sqlgraph.To(warehouse.Table, warehouse.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stockitem.WarehouseTable, stockitem.WarehouseColumn),
		)
		fromU = sqlgraph.SetNeighbors(siq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StockItem entity from the query.
// Returns a *NotFoundError when no StockItem was found.
func (siq *StockItemQuery) First(ctx context.Context) (*StockItem, error) {
	nodes, err := siq.Limit(1).All(setContextOp(ctx, siq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stockitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (siq *StockItemQuery) FirstX(ctx context.Context) *StockItem {
	node, err := siq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StockItem ID from the query.
// Returns a *NotFoundError when no StockItem ID was found.
func (siq *StockItemQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = siq.Limit(1).IDs(setContextOp(ctx, siq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stockitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (siq *StockItemQuery) FirstIDX(ctx context.Context) int64 {
	id, err := siq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StockItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StockItem entity is found.
// Returns a *NotFoundError when no StockItem entities are found.
func (siq *StockItemQuery) Only(ctx context.Context) (*StockItem, error) {
	nodes, err := siq.Limit(2).All(setContextOp(ctx, siq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stockitem.Label}
	default:
		return nil, &NotSingularError{stockitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (siq *StockItemQuery) OnlyX(ctx context.Context) *StockItem {
	node, err := siq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StockItem ID in the query.
// Returns a *NotSingularError when more than one StockItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (siq *StockItemQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = siq.Limit(2).IDs(setContextOp(ctx, siq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stockitem.Label}
	default:
		err = &NotSingularError{stockitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (siq *StockItemQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := siq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StockItems.
func (siq *StockItemQuery) All(ctx context.Context) ([]*StockItem, error) {
	ctx = setContextOp(ctx, siq.ctx, ent.OpQueryAll)
	if err := siq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StockItem, *StockItemQuery]()
	return withInterceptors[[]*StockItem](ctx, siq, qr, siq.inters)
}

// AllX is like All, but panics if an error occurs.
func (siq *StockItemQuery) AllX(ctx context.Context) []*StockItem {
	nodes, err := siq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StockItem IDs.
func (siq *StockItemQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if siq.ctx.Unique == nil && siq.path != nil {
		siq.Unique(true)
	}
	ctx = setContextOp(ctx, siq.ctx, ent.OpQueryIDs)
	if err = siq.Select(stockitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (siq *StockItemQuery) IDsX(ctx context.Context) []int64 {
	ids, err := siq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (siq *StockItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, siq.ctx, ent.OpQueryCount)
	if err := siq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, siq, querierCount[*StockItemQuery](), siq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (siq *StockItemQuery) CountX(ctx context.Context) int {
	count, err := siq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (siq *StockItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, siq.ctx, ent.OpQueryExist)
	switch _, err := siq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (siq *StockItemQuery) ExistX(ctx context.Context) bool {
	exist, err := siq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StockItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (siq *StockItemQuery) Clone() *StockItemQuery {
	if siq == nil {
		return nil
	}
	return &StockItemQuery{
		config:        siq.config,
		ctx:           siq.ctx.Clone(),
		order:         append([]stockitem.OrderOption{}, siq.order...),
		inters:        append([]Interceptor{}, siq.inters...),
		predicates:    append([]predicate.StockItem{}, siq.predicates...),
		withWarehouse: siq.withWarehouse.Clone(),
		// clone intermediate query.
		sql:  siq.sql.Clone(),
		path: siq.path,
	}
}

// WithWarehouse tells the query-builder to eager-load the nodes that are connected to
// the "warehouse" edge. The optional arguments are used to configure the query builder of the edge.
func (siq *StockItemQuery) WithWarehouse(opts ...func(*WarehouseQuery)) *StockItemQuery {
	query := (&WarehouseClient{config: siq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	siq.withWarehouse = query
	return siq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StockItem.Query().
//		GroupBy(stockitem.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (siq *StockItemQuery) GroupBy(field string, fields ...string) *StockItemGroupBy {
	siq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StockItemGroupBy{build: siq}
	grbuild.flds = &siq.ctx.Fields
	grbuild.label = stockitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.StockItem.Query().
//		Select(stockitem.FieldCreatedAt).
//		Scan(ctx, &v)
func (siq *StockItemQuery) Select(fields ...string) *StockItemSelect {
	siq.ctx.Fields = append(siq.ctx.Fields, fields...)
	sbuild := &StockItemSelect{StockItemQuery: siq}
	sbuild.label = stockitem.Label
	sbuild.flds, sbuild.scan = &siq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StockItemSelect configured with the given aggregations.
func (siq *StockItemQuery) Aggregate(fns ...AggregateFunc) *StockItemSelect {
	return siq.Select().Aggregate(fns...)
}

func (siq *StockItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range siq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, siq); err != nil {
				return err
			}
		}
	}
	for _, f := range siq.ctx.Fields {
		if !stockitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if siq.path != nil {
		prev, err := siq.path(ctx)
		if err != nil {
			return err
		}
		siq.sql = prev
	}
	return nil
}

func (siq *StockItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StockItem, error) {
	var (
		nodes       = []*StockItem{}
		_spec       = siq.querySpec()
		loadedTypes = [1]bool{
			siq.withWarehouse != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StockItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StockItem{config: siq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(siq.modifiers) > 0 {
		_spec.Modifiers = siq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, siq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := siq.withWarehouse; query != nil {
		if err := siq.loadWarehouse(ctx, query, nodes, nil,
			func(n *StockItem, e *Warehouse) { n.Edges.Warehouse = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (siq *StockItemQuery) loadWarehouse(ctx context.Context, query *WarehouseQuery, nodes []*StockItem, init func(*StockItem), assign func(*StockItem, *Warehouse)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*StockItem)
	for i := range nodes {
		fk := nodes[i].WarehouseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(warehouse.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "warehouse_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (siq *StockItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := siq.querySpec()
	if len(siq.modifiers) > 0 {
		_spec.Modifiers = siq.modifiers
	}
	_spec.Node.Columns = siq.ctx.Fields
	if len(siq.ctx.Fields) > 0 {
		_spec.Unique = siq.ctx.Unique != nil && *siq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, siq.driver, _spec)
}

func (siq *StockItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stockitem.Table, stockitem.Columns, sqlgraph.NewFieldSpec(stockitem.FieldID, field.TypeInt64))
	_spec.From = siq.sql
	if unique := siq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if siq.path != nil {
		_spec.Unique = true
	}
	if fields := siq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stockitem.FieldID)
		for i := range fields {
			if fields[i] != stockitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if siq.withWarehouse != nil {
			_spec.Node.AddColumnOnce(stockitem.FieldWarehouseID)
		}
	}
	if ps := siq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := siq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := siq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := siq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (siq *StockItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(siq.driver.Dialect())
	t1 := builder.Table(stockitem.Table)
	columns := siq.ctx.Fields
	if len(columns) == 0 {
		columns = stockitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if siq.sql != nil {
		selector = siq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if siq.ctx.Unique != nil && *siq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range siq.modifiers {
		m(selector)
	}
	for _, p := range siq.predicates {
		p(selector)
	}
	for _, p := range siq.order {
		p(selector)
	}
	if offset := siq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := siq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (siq *StockItemQuery) Modify(modifiers ...func(s *sql.Selector)) *StockItemSelect {
	siq.modifiers = append(siq.modifiers, modifiers...)
	return siq.Select()
}

// StockItemGroupBy is the group-by builder for StockItem entities.
type StockItemGroupBy struct {
	selector
	build *StockItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sigb *StockItemGroupBy) Aggregate(fns ...AggregateFunc) *StockItemGroupBy {
	sigb.fns = append(sigb.fns, fns...)
	return sigb
}

// Scan applies the selector query and scans the result into the given value.
func (sigb *StockItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sigb.build.ctx, ent.OpQueryGroupBy)
	if err := sigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockItemQuery, *StockItemGroupBy](ctx, sigb.build, sigb, sigb.build.inters, v)
}

func (sigb *StockItemGroupBy) sqlScan(ctx context.Context, root *StockItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sigb.fns))
	for _, fn := range sigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sigb.flds)+len(sigb.fns))
		for _, f := range *sigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StockItemSelect is the builder for selecting fields of StockItem entities.
type StockItemSelect struct {
	*StockItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sis *StockItemSelect) Aggregate(fns ...AggregateFunc) *StockItemSelect {
	sis.fns = append(sis.fns, fns...)
	return sis
}

// Scan applies the selector query and scans the result into the given value.
func (sis *StockItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sis.ctx, ent.OpQuerySelect)
	if err := sis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockItemQuery, *StockItemSelect](ctx, sis.StockItemQuery, sis, sis.inters, v)
}

func (sis *StockItemSelect) sqlScan(ctx context.Context, root *StockItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sis.fns))
	for _, fn := range sis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sis *StockItemSelect) Modify(modifiers ...func(s *sql.Selector)) *StockItemSelect {
	sis.modifiers = append(sis.modifiers, modifiers...)
	return sis
}
