// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/warehouse/ent/enum"
	"github.com/makesalekz/warehouse/ent/inventory"
	"github.com/makesalekz/warehouse/ent/predicate"
	"github.com/makesalekz/warehouse/ent/stockitem"
	"github.com/makesalekz/warehouse/ent/stockmovement"
	"github.com/makesalekz/warehouse/ent/warehouse"
)

// WarehouseUpdate is the builder for updating Warehouse entities.
type WarehouseUpdate struct {
	config
	hooks     []Hook
	mutation  *WarehouseMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the WarehouseUpdate builder.
func (wu *WarehouseUpdate) Where(ps ...predicate.Warehouse) *WarehouseUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WarehouseUpdate) SetUpdatedAt(t time.Time) *WarehouseUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// SetDeletedAt sets the "deleted_at" field.
func (wu *WarehouseUpdate) SetDeletedAt(t time.Time) *WarehouseUpdate {
	wu.mutation.SetDeletedAt(t)
	return wu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (wu *WarehouseUpdate) SetNillableDeletedAt(t *time.Time) *WarehouseUpdate {
	if t != nil {
		wu.SetDeletedAt(*t)
	}
	return wu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (wu *WarehouseUpdate) ClearDeletedAt() *WarehouseUpdate {
	wu.mutation.ClearDeletedAt()
	return wu
}

// SetName sets the "name" field.
func (wu *WarehouseUpdate) SetName(s string) *WarehouseUpdate {
	wu.mutation.SetName(s)
	return wu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wu *WarehouseUpdate) SetNillableName(s *string) *WarehouseUpdate {
	if s != nil {
		wu.SetName(*s)
	}
	return wu
}

// SetType sets the "type" field.
func (wu *WarehouseUpdate) SetType(et enum.WarehouseType) *WarehouseUpdate {
	wu.mutation.SetType(et)
	return wu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (wu *WarehouseUpdate) SetNillableType(et *enum.WarehouseType) *WarehouseUpdate {
	if et != nil {
		wu.SetType(*et)
	}
	return wu
}

// SetDescription sets the "description" field.
func (wu *WarehouseUpdate) SetDescription(s string) *WarehouseUpdate {
	wu.mutation.SetDescription(s)
	return wu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wu *WarehouseUpdate) SetNillableDescription(s *string) *WarehouseUpdate {
	if s != nil {
		wu.SetDescription(*s)
	}
	return wu
}

// ClearDescription clears the value of the "description" field.
func (wu *WarehouseUpdate) ClearDescription() *WarehouseUpdate {
	wu.mutation.ClearDescription()
	return wu
}

// SetAddress sets the "address" field.
func (wu *WarehouseUpdate) SetAddress(s string) *WarehouseUpdate {
	wu.mutation.SetAddress(s)
	return wu
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (wu *WarehouseUpdate) SetNillableAddress(s *string) *WarehouseUpdate {
	if s != nil {
		wu.SetAddress(*s)
	}
	return wu
}

// ClearAddress clears the value of the "address" field.
func (wu *WarehouseUpdate) ClearAddress() *WarehouseUpdate {
	wu.mutation.ClearAddress()
	return wu
}

// SetIsActive sets the "is_active" field.
func (wu *WarehouseUpdate) SetIsActive(b bool) *WarehouseUpdate {
	wu.mutation.SetIsActive(b)
	return wu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (wu *WarehouseUpdate) SetNillableIsActive(b *bool) *WarehouseUpdate {
	if b != nil {
		wu.SetIsActive(*b)
	}
	return wu
}

// SetStoreID sets the "store_id" field.
func (wu *WarehouseUpdate) SetStoreID(i int64) *WarehouseUpdate {
	wu.mutation.ResetStoreID()
	wu.mutation.SetStoreID(i)
	return wu
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (wu *WarehouseUpdate) SetNillableStoreID(i *int64) *WarehouseUpdate {
	if i != nil {
		wu.SetStoreID(*i)
	}
	return wu
}

// AddStoreID adds i to the "store_id" field.
func (wu *WarehouseUpdate) AddStoreID(i int64) *WarehouseUpdate {
	wu.mutation.AddStoreID(i)
	return wu
}

// ClearStoreID clears the value of the "store_id" field.
func (wu *WarehouseUpdate) ClearStoreID() *WarehouseUpdate {
	wu.mutation.ClearStoreID()
	return wu
}

// AddStockItemIDs adds the "stock_items" edge to the StockItem entity by IDs.
func (wu *WarehouseUpdate) AddStockItemIDs(ids ...int64) *WarehouseUpdate {
	wu.mutation.AddStockItemIDs(ids...)
	return wu
}

// AddStockItems adds the "stock_items" edges to the StockItem entity.
func (wu *WarehouseUpdate) AddStockItems(s ...*StockItem) *WarehouseUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wu.AddStockItemIDs(ids...)
}

// AddStockMovementIDs adds the "stock_movements" edge to the StockMovement entity by IDs.
func (wu *WarehouseUpdate) AddStockMovementIDs(ids ...int64) *WarehouseUpdate {
	wu.mutation.AddStockMovementIDs(ids...)
	return wu
}

// AddStockMovements adds the "stock_movements" edges to the StockMovement entity.
func (wu *WarehouseUpdate) AddStockMovements(s ...*StockMovement) *WarehouseUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wu.AddStockMovementIDs(ids...)
}

// AddInventoryIDs adds the "inventories" edge to the Inventory entity by IDs.
func (wu *WarehouseUpdate) AddInventoryIDs(ids ...int64) *WarehouseUpdate {
	wu.mutation.AddInventoryIDs(ids...)
	return wu
}

// AddInventories adds the "inventories" edges to the Inventory entity.
func (wu *WarehouseUpdate) AddInventories(i ...*Inventory) *WarehouseUpdate {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return wu.AddInventoryIDs(ids...)
}

// Mutation returns the WarehouseMutation object of the builder.
func (wu *WarehouseUpdate) Mutation() *WarehouseMutation {
	return wu.mutation
}

// ClearStockItems clears all "stock_items" edges to the StockItem entity.
func (wu *WarehouseUpdate) ClearStockItems() *WarehouseUpdate {
	wu.mutation.ClearStockItems()
	return wu
}

// RemoveStockItemIDs removes the "stock_items" edge to StockItem entities by IDs.
func (wu *WarehouseUpdate) RemoveStockItemIDs(ids ...int64) *WarehouseUpdate {
	wu.mutation.RemoveStockItemIDs(ids...)
	return wu
}

// RemoveStockItems removes "stock_items" edges to StockItem entities.
func (wu *WarehouseUpdate) RemoveStockItems(s ...*StockItem) *WarehouseUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wu.RemoveStockItemIDs(ids...)
}

// ClearStockMovements clears all "stock_movements" edges to the StockMovement entity.
func (wu *WarehouseUpdate) ClearStockMovements() *WarehouseUpdate {
	wu.mutation.ClearStockMovements()
	return wu
}

// RemoveStockMovementIDs removes the "stock_movements" edge to StockMovement entities by IDs.
func (wu *WarehouseUpdate) RemoveStockMovementIDs(ids ...int64) *WarehouseUpdate {
	wu.mutation.RemoveStockMovementIDs(ids...)
	return wu
}

// RemoveStockMovements removes "stock_movements" edges to StockMovement entities.
func (wu *WarehouseUpdate) RemoveStockMovements(s ...*StockMovement) *WarehouseUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wu.RemoveStockMovementIDs(ids...)
}

// ClearInventories clears all "inventories" edges to the Inventory entity.
func (wu *WarehouseUpdate) ClearInventories() *WarehouseUpdate {
	wu.mutation.ClearInventories()
	return wu
}

// RemoveInventoryIDs removes the "inventories" edge to Inventory entities by IDs.
func (wu *WarehouseUpdate) RemoveInventoryIDs(ids ...int64) *WarehouseUpdate {
	wu.mutation.RemoveInventoryIDs(ids...)
	return wu
}

// RemoveInventories removes "inventories" edges to Inventory entities.
func (wu *WarehouseUpdate) RemoveInventories(i ...*Inventory) *WarehouseUpdate {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return wu.RemoveInventoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WarehouseUpdate) Save(ctx context.Context) (int, error) {
	if err := wu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WarehouseUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WarehouseUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WarehouseUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wu *WarehouseUpdate) defaults() error {
	if _, ok := wu.mutation.UpdatedAt(); !ok {
		if warehouse.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized warehouse.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := warehouse.UpdateDefaultUpdatedAt()
		wu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (wu *WarehouseUpdate) check() error {
	if v, ok := wu.mutation.Name(); ok {
		if err := warehouse.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Warehouse.name": %w`, err)}
		}
	}
	if v, ok := wu.mutation.GetType(); ok {
		if err := warehouse.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Warehouse.type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (wu *WarehouseUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WarehouseUpdate {
	wu.modifiers = append(wu.modifiers, modifiers...)
	return wu
}

func (wu *WarehouseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(warehouse.Table, warehouse.Columns, sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt64))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.SetField(warehouse.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wu.mutation.DeletedAt(); ok {
		_spec.SetField(warehouse.FieldDeletedAt, field.TypeTime, value)
	}
	if wu.mutation.DeletedAtCleared() {
		_spec.ClearField(warehouse.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := wu.mutation.Name(); ok {
		_spec.SetField(warehouse.FieldName, field.TypeString, value)
	}
	if value, ok := wu.mutation.GetType(); ok {
		_spec.SetField(warehouse.FieldType, field.TypeEnum, value)
	}
	if value, ok := wu.mutation.Description(); ok {
		_spec.SetField(warehouse.FieldDescription, field.TypeString, value)
	}
	if wu.mutation.DescriptionCleared() {
		_spec.ClearField(warehouse.FieldDescription, field.TypeString)
	}
	if value, ok := wu.mutation.Address(); ok {
		_spec.SetField(warehouse.FieldAddress, field.TypeString, value)
	}
	if wu.mutation.AddressCleared() {
		_spec.ClearField(warehouse.FieldAddress, field.TypeString)
	}
	if value, ok := wu.mutation.IsActive(); ok {
		_spec.SetField(warehouse.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := wu.mutation.StoreID(); ok {
		_spec.SetField(warehouse.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedStoreID(); ok {
		_spec.AddField(warehouse.FieldStoreID, field.TypeInt64, value)
	}
	if wu.mutation.StoreIDCleared() {
		_spec.ClearField(warehouse.FieldStoreID, field.TypeInt64)
	}
	if wu.mutation.StockItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockItemsTable,
			Columns: []string{warehouse.StockItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedStockItemsIDs(); len(nodes) > 0 && !wu.mutation.StockItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockItemsTable,
			Columns: []string{warehouse.StockItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.StockItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockItemsTable,
			Columns: []string{warehouse.StockItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.StockMovementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockMovementsTable,
			Columns: []string{warehouse.StockMovementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockmovement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedStockMovementsIDs(); len(nodes) > 0 && !wu.mutation.StockMovementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockMovementsTable,
			Columns: []string{warehouse.StockMovementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockmovement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.StockMovementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockMovementsTable,
			Columns: []string{warehouse.StockMovementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockmovement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.InventoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.InventoriesTable,
			Columns: []string{warehouse.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedInventoriesIDs(); len(nodes) > 0 && !wu.mutation.InventoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.InventoriesTable,
			Columns: []string{warehouse.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.InventoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.InventoriesTable,
			Columns: []string{warehouse.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(wu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{warehouse.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WarehouseUpdateOne is the builder for updating a single Warehouse entity.
type WarehouseUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *WarehouseMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WarehouseUpdateOne) SetUpdatedAt(t time.Time) *WarehouseUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// SetDeletedAt sets the "deleted_at" field.
func (wuo *WarehouseUpdateOne) SetDeletedAt(t time.Time) *WarehouseUpdateOne {
	wuo.mutation.SetDeletedAt(t)
	return wuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (wuo *WarehouseUpdateOne) SetNillableDeletedAt(t *time.Time) *WarehouseUpdateOne {
	if t != nil {
		wuo.SetDeletedAt(*t)
	}
	return wuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (wuo *WarehouseUpdateOne) ClearDeletedAt() *WarehouseUpdateOne {
	wuo.mutation.ClearDeletedAt()
	return wuo
}

// SetName sets the "name" field.
func (wuo *WarehouseUpdateOne) SetName(s string) *WarehouseUpdateOne {
	wuo.mutation.SetName(s)
	return wuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wuo *WarehouseUpdateOne) SetNillableName(s *string) *WarehouseUpdateOne {
	if s != nil {
		wuo.SetName(*s)
	}
	return wuo
}

// SetType sets the "type" field.
func (wuo *WarehouseUpdateOne) SetType(et enum.WarehouseType) *WarehouseUpdateOne {
	wuo.mutation.SetType(et)
	return wuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (wuo *WarehouseUpdateOne) SetNillableType(et *enum.WarehouseType) *WarehouseUpdateOne {
	if et != nil {
		wuo.SetType(*et)
	}
	return wuo
}

// SetDescription sets the "description" field.
func (wuo *WarehouseUpdateOne) SetDescription(s string) *WarehouseUpdateOne {
	wuo.mutation.SetDescription(s)
	return wuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wuo *WarehouseUpdateOne) SetNillableDescription(s *string) *WarehouseUpdateOne {
	if s != nil {
		wuo.SetDescription(*s)
	}
	return wuo
}

// ClearDescription clears the value of the "description" field.
func (wuo *WarehouseUpdateOne) ClearDescription() *WarehouseUpdateOne {
	wuo.mutation.ClearDescription()
	return wuo
}

// SetAddress sets the "address" field.
func (wuo *WarehouseUpdateOne) SetAddress(s string) *WarehouseUpdateOne {
	wuo.mutation.SetAddress(s)
	return wuo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (wuo *WarehouseUpdateOne) SetNillableAddress(s *string) *WarehouseUpdateOne {
	if s != nil {
		wuo.SetAddress(*s)
	}
	return wuo
}

// ClearAddress clears the value of the "address" field.
func (wuo *WarehouseUpdateOne) ClearAddress() *WarehouseUpdateOne {
	wuo.mutation.ClearAddress()
	return wuo
}

// SetIsActive sets the "is_active" field.
func (wuo *WarehouseUpdateOne) SetIsActive(b bool) *WarehouseUpdateOne {
	wuo.mutation.SetIsActive(b)
	return wuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (wuo *WarehouseUpdateOne) SetNillableIsActive(b *bool) *WarehouseUpdateOne {
	if b != nil {
		wuo.SetIsActive(*b)
	}
	return wuo
}

// SetStoreID sets the "store_id" field.
func (wuo *WarehouseUpdateOne) SetStoreID(i int64) *WarehouseUpdateOne {
	wuo.mutation.ResetStoreID()
	wuo.mutation.SetStoreID(i)
	return wuo
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (wuo *WarehouseUpdateOne) SetNillableStoreID(i *int64) *WarehouseUpdateOne {
	if i != nil {
		wuo.SetStoreID(*i)
	}
	return wuo
}

// AddStoreID adds i to the "store_id" field.
func (wuo *WarehouseUpdateOne) AddStoreID(i int64) *WarehouseUpdateOne {
	wuo.mutation.AddStoreID(i)
	return wuo
}

// ClearStoreID clears the value of the "store_id" field.
func (wuo *WarehouseUpdateOne) ClearStoreID() *WarehouseUpdateOne {
	wuo.mutation.ClearStoreID()
	return wuo
}

// AddStockItemIDs adds the "stock_items" edge to the StockItem entity by IDs.
func (wuo *WarehouseUpdateOne) AddStockItemIDs(ids ...int64) *WarehouseUpdateOne {
	wuo.mutation.AddStockItemIDs(ids...)
	return wuo
}

// AddStockItems adds the "stock_items" edges to the StockItem entity.
func (wuo *WarehouseUpdateOne) AddStockItems(s ...*StockItem) *WarehouseUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wuo.AddStockItemIDs(ids...)
}

// AddStockMovementIDs adds the "stock_movements" edge to the StockMovement entity by IDs.
func (wuo *WarehouseUpdateOne) AddStockMovementIDs(ids ...int64) *WarehouseUpdateOne {
	wuo.mutation.AddStockMovementIDs(ids...)
	return wuo
}

// AddStockMovements adds the "stock_movements" edges to the StockMovement entity.
func (wuo *WarehouseUpdateOne) AddStockMovements(s ...*StockMovement) *WarehouseUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wuo.AddStockMovementIDs(ids...)
}

// AddInventoryIDs adds the "inventories" edge to the Inventory entity by IDs.
func (wuo *WarehouseUpdateOne) AddInventoryIDs(ids ...int64) *WarehouseUpdateOne {
	wuo.mutation.AddInventoryIDs(ids...)
	return wuo
}

// AddInventories adds the "inventories" edges to the Inventory entity.
func (wuo *WarehouseUpdateOne) AddInventories(i ...*Inventory) *WarehouseUpdateOne {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return wuo.AddInventoryIDs(ids...)
}

// Mutation returns the WarehouseMutation object of the builder.
func (wuo *WarehouseUpdateOne) Mutation() *WarehouseMutation {
	return wuo.mutation
}

// ClearStockItems clears all "stock_items" edges to the StockItem entity.
func (wuo *WarehouseUpdateOne) ClearStockItems() *WarehouseUpdateOne {
	wuo.mutation.ClearStockItems()
	return wuo
}

// RemoveStockItemIDs removes the "stock_items" edge to StockItem entities by IDs.
func (wuo *WarehouseUpdateOne) RemoveStockItemIDs(ids ...int64) *WarehouseUpdateOne {
	wuo.mutation.RemoveStockItemIDs(ids...)
	return wuo
}

// RemoveStockItems removes "stock_items" edges to StockItem entities.
func (wuo *WarehouseUpdateOne) RemoveStockItems(s ...*StockItem) *WarehouseUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wuo.RemoveStockItemIDs(ids...)
}

// ClearStockMovements clears all "stock_movements" edges to the StockMovement entity.
func (wuo *WarehouseUpdateOne) ClearStockMovements() *WarehouseUpdateOne {
	wuo.mutation.ClearStockMovements()
	return wuo
}

// RemoveStockMovementIDs removes the "stock_movements" edge to StockMovement entities by IDs.
func (wuo *WarehouseUpdateOne) RemoveStockMovementIDs(ids ...int64) *WarehouseUpdateOne {
	wuo.mutation.RemoveStockMovementIDs(ids...)
	return wuo
}

// RemoveStockMovements removes "stock_movements" edges to StockMovement entities.
func (wuo *WarehouseUpdateOne) RemoveStockMovements(s ...*StockMovement) *WarehouseUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return wuo.RemoveStockMovementIDs(ids...)
}

// ClearInventories clears all "inventories" edges to the Inventory entity.
func (wuo *WarehouseUpdateOne) ClearInventories() *WarehouseUpdateOne {
	wuo.mutation.ClearInventories()
	return wuo
}

// RemoveInventoryIDs removes the "inventories" edge to Inventory entities by IDs.
func (wuo *WarehouseUpdateOne) RemoveInventoryIDs(ids ...int64) *WarehouseUpdateOne {
	wuo.mutation.RemoveInventoryIDs(ids...)
	return wuo
}

// RemoveInventories removes "inventories" edges to Inventory entities.
func (wuo *WarehouseUpdateOne) RemoveInventories(i ...*Inventory) *WarehouseUpdateOne {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return wuo.RemoveInventoryIDs(ids...)
}

// Where appends a list predicates to the WarehouseUpdate builder.
func (wuo *WarehouseUpdateOne) Where(ps ...predicate.Warehouse) *WarehouseUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WarehouseUpdateOne) Select(field string, fields ...string) *WarehouseUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Warehouse entity.
func (wuo *WarehouseUpdateOne) Save(ctx context.Context) (*Warehouse, error) {
	if err := wuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WarehouseUpdateOne) SaveX(ctx context.Context) *Warehouse {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WarehouseUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WarehouseUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wuo *WarehouseUpdateOne) defaults() error {
	if _, ok := wuo.mutation.UpdatedAt(); !ok {
		if warehouse.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized warehouse.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := warehouse.UpdateDefaultUpdatedAt()
		wuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WarehouseUpdateOne) check() error {
	if v, ok := wuo.mutation.Name(); ok {
		if err := warehouse.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Warehouse.name": %w`, err)}
		}
	}
	if v, ok := wuo.mutation.GetType(); ok {
		if err := warehouse.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Warehouse.type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (wuo *WarehouseUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WarehouseUpdateOne {
	wuo.modifiers = append(wuo.modifiers, modifiers...)
	return wuo
}

func (wuo *WarehouseUpdateOne) sqlSave(ctx context.Context) (_node *Warehouse, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(warehouse.Table, warehouse.Columns, sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt64))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Warehouse.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, warehouse.FieldID)
		for _, f := range fields {
			if !warehouse.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != warehouse.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.SetField(warehouse.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wuo.mutation.DeletedAt(); ok {
		_spec.SetField(warehouse.FieldDeletedAt, field.TypeTime, value)
	}
	if wuo.mutation.DeletedAtCleared() {
		_spec.ClearField(warehouse.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := wuo.mutation.Name(); ok {
		_spec.SetField(warehouse.FieldName, field.TypeString, value)
	}
	if value, ok := wuo.mutation.GetType(); ok {
		_spec.SetField(warehouse.FieldType, field.TypeEnum, value)
	}
	if value, ok := wuo.mutation.Description(); ok {
		_spec.SetField(warehouse.FieldDescription, field.TypeString, value)
	}
	if wuo.mutation.DescriptionCleared() {
		_spec.ClearField(warehouse.FieldDescription, field.TypeString)
	}
	if value, ok := wuo.mutation.Address(); ok {
		_spec.SetField(warehouse.FieldAddress, field.TypeString, value)
	}
	if wuo.mutation.AddressCleared() {
		_spec.ClearField(warehouse.FieldAddress, field.TypeString)
	}
	if value, ok := wuo.mutation.IsActive(); ok {
		_spec.SetField(warehouse.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := wuo.mutation.StoreID(); ok {
		_spec.SetField(warehouse.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedStoreID(); ok {
		_spec.AddField(warehouse.FieldStoreID, field.TypeInt64, value)
	}
	if wuo.mutation.StoreIDCleared() {
		_spec.ClearField(warehouse.FieldStoreID, field.TypeInt64)
	}
	if wuo.mutation.StockItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockItemsTable,
			Columns: []string{warehouse.StockItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedStockItemsIDs(); len(nodes) > 0 && !wuo.mutation.StockItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockItemsTable,
			Columns: []string{warehouse.StockItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.StockItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockItemsTable,
			Columns: []string{warehouse.StockItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.StockMovementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockMovementsTable,
			Columns: []string{warehouse.StockMovementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockmovement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedStockMovementsIDs(); len(nodes) > 0 && !wuo.mutation.StockMovementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockMovementsTable,
			Columns: []string{warehouse.StockMovementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockmovement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.StockMovementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.StockMovementsTable,
			Columns: []string{warehouse.StockMovementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockmovement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.InventoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.InventoriesTable,
			Columns: []string{warehouse.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedInventoriesIDs(); len(nodes) > 0 && !wuo.mutation.InventoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.InventoriesTable,
			Columns: []string{warehouse.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.InventoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.InventoriesTable,
			Columns: []string{warehouse.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(wuo.modifiers...)
	_node = &Warehouse{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{warehouse.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
