// Code generated by ent, DO NOT EDIT.

package stockitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/warehouse/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldTenantID, v))
}

// WarehouseID applies equality check predicate on the "warehouse_id" field. It's identical to WarehouseIDEQ.
func WarehouseID(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldWarehouseID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldProductID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldQuantity, v))
}

// MinQuantity applies equality check predicate on the "min_quantity" field. It's identical to MinQuantityEQ.
func MinQuantity(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldMinQuantity, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StockItem {
	return predicate.StockItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldLTE(FieldTenantID, v))
}

// WarehouseIDEQ applies the EQ predicate on the "warehouse_id" field.
func WarehouseIDEQ(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldWarehouseID, v))
}

// WarehouseIDNEQ applies the NEQ predicate on the "warehouse_id" field.
func WarehouseIDNEQ(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldNEQ(FieldWarehouseID, v))
}

// WarehouseIDIn applies the In predicate on the "warehouse_id" field.
func WarehouseIDIn(vs ...int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldIn(FieldWarehouseID, vs...))
}

// WarehouseIDNotIn applies the NotIn predicate on the "warehouse_id" field.
func WarehouseIDNotIn(vs ...int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldNotIn(FieldWarehouseID, vs...))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int64) predicate.StockItem {
	return predicate.StockItem(sql.FieldLTE(FieldProductID, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldLTE(FieldQuantity, v))
}

// QuantityIsNil applies the IsNil predicate on the "quantity" field.
func QuantityIsNil() predicate.StockItem {
	return predicate.StockItem(sql.FieldIsNull(FieldQuantity))
}

// QuantityNotNil applies the NotNil predicate on the "quantity" field.
func QuantityNotNil() predicate.StockItem {
	return predicate.StockItem(sql.FieldNotNull(FieldQuantity))
}

// MinQuantityEQ applies the EQ predicate on the "min_quantity" field.
func MinQuantityEQ(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldEQ(FieldMinQuantity, v))
}

// MinQuantityNEQ applies the NEQ predicate on the "min_quantity" field.
func MinQuantityNEQ(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldNEQ(FieldMinQuantity, v))
}

// MinQuantityIn applies the In predicate on the "min_quantity" field.
func MinQuantityIn(vs ...decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldIn(FieldMinQuantity, vs...))
}

// MinQuantityNotIn applies the NotIn predicate on the "min_quantity" field.
func MinQuantityNotIn(vs ...decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldNotIn(FieldMinQuantity, vs...))
}

// MinQuantityGT applies the GT predicate on the "min_quantity" field.
func MinQuantityGT(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldGT(FieldMinQuantity, v))
}

// MinQuantityGTE applies the GTE predicate on the "min_quantity" field.
func MinQuantityGTE(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldGTE(FieldMinQuantity, v))
}

// MinQuantityLT applies the LT predicate on the "min_quantity" field.
func MinQuantityLT(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldLT(FieldMinQuantity, v))
}

// MinQuantityLTE applies the LTE predicate on the "min_quantity" field.
func MinQuantityLTE(v decimal.Decimal) predicate.StockItem {
	return predicate.StockItem(sql.FieldLTE(FieldMinQuantity, v))
}

// MinQuantityIsNil applies the IsNil predicate on the "min_quantity" field.
func MinQuantityIsNil() predicate.StockItem {
	return predicate.StockItem(sql.FieldIsNull(FieldMinQuantity))
}

// MinQuantityNotNil applies the NotNil predicate on the "min_quantity" field.
func MinQuantityNotNil() predicate.StockItem {
	return predicate.StockItem(sql.FieldNotNull(FieldMinQuantity))
}

// HasWarehouse applies the HasEdge predicate on the "warehouse" edge.
func HasWarehouse() predicate.StockItem {
	return predicate.StockItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WarehouseTable, WarehouseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWarehouseWith applies the HasEdge predicate on the "warehouse" edge with a given conditions (other predicates).
func HasWarehouseWith(preds ...predicate.Warehouse) predicate.StockItem {
	return predicate.StockItem(func(s *sql.Selector) {
		step := newWarehouseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StockItem) predicate.StockItem {
	return predicate.StockItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StockItem) predicate.StockItem {
	return predicate.StockItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StockItem) predicate.StockItem {
	return predicate.StockItem(sql.NotPredicates(p))
}
