// Code generated by ent, DO NOT EDIT.

package inventoryitem

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the inventoryitem type in the database.
	Label = "inventory_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInventoryID holds the string denoting the inventory_id field in the database.
	FieldInventoryID = "inventory_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldExpectedQty holds the string denoting the expected_qty field in the database.
	FieldExpectedQty = "expected_qty"
	// FieldActualQty holds the string denoting the actual_qty field in the database.
	FieldActualQty = "actual_qty"
	// FieldDifference holds the string denoting the difference field in the database.
	FieldDifference = "difference"
	// EdgeInventory holds the string denoting the inventory edge name in mutations.
	EdgeInventory = "inventory"
	// Table holds the table name of the inventoryitem in the database.
	Table = "inventory_items"
	// InventoryTable is the table that holds the inventory relation/edge.
	InventoryTable = "inventory_items"
	// InventoryInverseTable is the table name for the Inventory entity.
	// It exists in this package in order to avoid circular dependency with the "inventory" package.
	InventoryInverseTable = "inventories"
	// InventoryColumn is the table column denoting the inventory relation/edge.
	InventoryColumn = "inventory_id"
)

// Columns holds all SQL columns for inventoryitem fields.
var Columns = []string{
	FieldID,
	FieldInventoryID,
	FieldProductID,
	FieldExpectedQty,
	FieldActualQty,
	FieldDifference,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the InventoryItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInventoryID orders the results by the inventory_id field.
func ByInventoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInventoryID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByExpectedQty orders the results by the expected_qty field.
func ByExpectedQty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedQty, opts...).ToFunc()
}

// ByActualQty orders the results by the actual_qty field.
func ByActualQty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualQty, opts...).ToFunc()
}

// ByDifference orders the results by the difference field.
func ByDifference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDifference, opts...).ToFunc()
}

// ByInventoryField orders the results by inventory field.
func ByInventoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInventoryStep(), sql.OrderByField(field, opts...))
	}
}
func newInventoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InventoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InventoryTable, InventoryColumn),
	)
}
