// Code generated by ent, DO NOT EDIT.

package inventoryitem

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/warehouse/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldLTE(FieldID, id))
}

// InventoryID applies equality check predicate on the "inventory_id" field. It's identical to InventoryIDEQ.
func InventoryID(v int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldInventoryID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldProductID, v))
}

// ExpectedQty applies equality check predicate on the "expected_qty" field. It's identical to ExpectedQtyEQ.
func ExpectedQty(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldExpectedQty, v))
}

// ActualQty applies equality check predicate on the "actual_qty" field. It's identical to ActualQtyEQ.
func ActualQty(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldActualQty, v))
}

// Difference applies equality check predicate on the "difference" field. It's identical to DifferenceEQ.
func Difference(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldDifference, v))
}

// InventoryIDEQ applies the EQ predicate on the "inventory_id" field.
func InventoryIDEQ(v int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldInventoryID, v))
}

// InventoryIDNEQ applies the NEQ predicate on the "inventory_id" field.
func InventoryIDNEQ(v int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNEQ(FieldInventoryID, v))
}

// InventoryIDIn applies the In predicate on the "inventory_id" field.
func InventoryIDIn(vs ...int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldIn(FieldInventoryID, vs...))
}

// InventoryIDNotIn applies the NotIn predicate on the "inventory_id" field.
func InventoryIDNotIn(vs ...int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNotIn(FieldInventoryID, vs...))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int64) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldLTE(FieldProductID, v))
}

// ExpectedQtyEQ applies the EQ predicate on the "expected_qty" field.
func ExpectedQtyEQ(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldExpectedQty, v))
}

// ExpectedQtyNEQ applies the NEQ predicate on the "expected_qty" field.
func ExpectedQtyNEQ(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNEQ(FieldExpectedQty, v))
}

// ExpectedQtyIn applies the In predicate on the "expected_qty" field.
func ExpectedQtyIn(vs ...decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldIn(FieldExpectedQty, vs...))
}

// ExpectedQtyNotIn applies the NotIn predicate on the "expected_qty" field.
func ExpectedQtyNotIn(vs ...decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNotIn(FieldExpectedQty, vs...))
}

// ExpectedQtyGT applies the GT predicate on the "expected_qty" field.
func ExpectedQtyGT(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldGT(FieldExpectedQty, v))
}

// ExpectedQtyGTE applies the GTE predicate on the "expected_qty" field.
func ExpectedQtyGTE(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldGTE(FieldExpectedQty, v))
}

// ExpectedQtyLT applies the LT predicate on the "expected_qty" field.
func ExpectedQtyLT(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldLT(FieldExpectedQty, v))
}

// ExpectedQtyLTE applies the LTE predicate on the "expected_qty" field.
func ExpectedQtyLTE(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldLTE(FieldExpectedQty, v))
}

// ActualQtyEQ applies the EQ predicate on the "actual_qty" field.
func ActualQtyEQ(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldActualQty, v))
}

// ActualQtyNEQ applies the NEQ predicate on the "actual_qty" field.
func ActualQtyNEQ(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNEQ(FieldActualQty, v))
}

// ActualQtyIn applies the In predicate on the "actual_qty" field.
func ActualQtyIn(vs ...decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldIn(FieldActualQty, vs...))
}

// ActualQtyNotIn applies the NotIn predicate on the "actual_qty" field.
func ActualQtyNotIn(vs ...decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNotIn(FieldActualQty, vs...))
}

// ActualQtyGT applies the GT predicate on the "actual_qty" field.
func ActualQtyGT(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldGT(FieldActualQty, v))
}

// ActualQtyGTE applies the GTE predicate on the "actual_qty" field.
func ActualQtyGTE(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldGTE(FieldActualQty, v))
}

// ActualQtyLT applies the LT predicate on the "actual_qty" field.
func ActualQtyLT(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldLT(FieldActualQty, v))
}

// ActualQtyLTE applies the LTE predicate on the "actual_qty" field.
func ActualQtyLTE(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldLTE(FieldActualQty, v))
}

// ActualQtyIsNil applies the IsNil predicate on the "actual_qty" field.
func ActualQtyIsNil() predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldIsNull(FieldActualQty))
}

// ActualQtyNotNil applies the NotNil predicate on the "actual_qty" field.
func ActualQtyNotNil() predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNotNull(FieldActualQty))
}

// DifferenceEQ applies the EQ predicate on the "difference" field.
func DifferenceEQ(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldEQ(FieldDifference, v))
}

// DifferenceNEQ applies the NEQ predicate on the "difference" field.
func DifferenceNEQ(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNEQ(FieldDifference, v))
}

// DifferenceIn applies the In predicate on the "difference" field.
func DifferenceIn(vs ...decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldIn(FieldDifference, vs...))
}

// DifferenceNotIn applies the NotIn predicate on the "difference" field.
func DifferenceNotIn(vs ...decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNotIn(FieldDifference, vs...))
}

// DifferenceGT applies the GT predicate on the "difference" field.
func DifferenceGT(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldGT(FieldDifference, v))
}

// DifferenceGTE applies the GTE predicate on the "difference" field.
func DifferenceGTE(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldGTE(FieldDifference, v))
}

// DifferenceLT applies the LT predicate on the "difference" field.
func DifferenceLT(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldLT(FieldDifference, v))
}

// DifferenceLTE applies the LTE predicate on the "difference" field.
func DifferenceLTE(v decimal.Decimal) predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldLTE(FieldDifference, v))
}

// DifferenceIsNil applies the IsNil predicate on the "difference" field.
func DifferenceIsNil() predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldIsNull(FieldDifference))
}

// DifferenceNotNil applies the NotNil predicate on the "difference" field.
func DifferenceNotNil() predicate.InventoryItem {
	return predicate.InventoryItem(sql.FieldNotNull(FieldDifference))
}

// HasInventory applies the HasEdge predicate on the "inventory" edge.
func HasInventory() predicate.InventoryItem {
	return predicate.InventoryItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InventoryTable, InventoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInventoryWith applies the HasEdge predicate on the "inventory" edge with a given conditions (other predicates).
func HasInventoryWith(preds ...predicate.Inventory) predicate.InventoryItem {
	return predicate.InventoryItem(func(s *sql.Selector) {
		step := newInventoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InventoryItem) predicate.InventoryItem {
	return predicate.InventoryItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InventoryItem) predicate.InventoryItem {
	return predicate.InventoryItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InventoryItem) predicate.InventoryItem {
	return predicate.InventoryItem(sql.NotPredicates(p))
}
