// Code generated by ent, DO NOT EDIT.

package stockmovement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/warehouse/ent/enum"
	"github.com/makesalekz/warehouse/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldTenantID, v))
}

// WarehouseID applies equality check predicate on the "warehouse_id" field. It's identical to WarehouseIDEQ.
func WarehouseID(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldWarehouseID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldProductID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v decimal.Decimal) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldQuantity, v))
}

// CounterpartyID applies equality check predicate on the "counterparty_id" field. It's identical to CounterpartyIDEQ.
func CounterpartyID(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldCounterpartyID, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldReason, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLTE(FieldTenantID, v))
}

// WarehouseIDEQ applies the EQ predicate on the "warehouse_id" field.
func WarehouseIDEQ(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldWarehouseID, v))
}

// WarehouseIDNEQ applies the NEQ predicate on the "warehouse_id" field.
func WarehouseIDNEQ(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNEQ(FieldWarehouseID, v))
}

// WarehouseIDIn applies the In predicate on the "warehouse_id" field.
func WarehouseIDIn(vs ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIn(FieldWarehouseID, vs...))
}

// WarehouseIDNotIn applies the NotIn predicate on the "warehouse_id" field.
func WarehouseIDNotIn(vs ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotIn(FieldWarehouseID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v enum.MovementType) predicate.StockMovement {
	vc := v
	return predicate.StockMovement(sql.FieldEQ(FieldType, vc))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v enum.MovementType) predicate.StockMovement {
	vc := v
	return predicate.StockMovement(sql.FieldNEQ(FieldType, vc))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...enum.MovementType) predicate.StockMovement {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.StockMovement(sql.FieldIn(FieldType, v...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...enum.MovementType) predicate.StockMovement {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.StockMovement(sql.FieldNotIn(FieldType, v...))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLTE(FieldProductID, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v decimal.Decimal) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v decimal.Decimal) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...decimal.Decimal) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...decimal.Decimal) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v decimal.Decimal) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v decimal.Decimal) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v decimal.Decimal) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v decimal.Decimal) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLTE(FieldQuantity, v))
}

// CounterpartyIDEQ applies the EQ predicate on the "counterparty_id" field.
func CounterpartyIDEQ(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldCounterpartyID, v))
}

// CounterpartyIDNEQ applies the NEQ predicate on the "counterparty_id" field.
func CounterpartyIDNEQ(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNEQ(FieldCounterpartyID, v))
}

// CounterpartyIDIn applies the In predicate on the "counterparty_id" field.
func CounterpartyIDIn(vs ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIn(FieldCounterpartyID, vs...))
}

// CounterpartyIDNotIn applies the NotIn predicate on the "counterparty_id" field.
func CounterpartyIDNotIn(vs ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotIn(FieldCounterpartyID, vs...))
}

// CounterpartyIDGT applies the GT predicate on the "counterparty_id" field.
func CounterpartyIDGT(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGT(FieldCounterpartyID, v))
}

// CounterpartyIDGTE applies the GTE predicate on the "counterparty_id" field.
func CounterpartyIDGTE(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGTE(FieldCounterpartyID, v))
}

// CounterpartyIDLT applies the LT predicate on the "counterparty_id" field.
func CounterpartyIDLT(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLT(FieldCounterpartyID, v))
}

// CounterpartyIDLTE applies the LTE predicate on the "counterparty_id" field.
func CounterpartyIDLTE(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLTE(FieldCounterpartyID, v))
}

// CounterpartyIDIsNil applies the IsNil predicate on the "counterparty_id" field.
func CounterpartyIDIsNil() predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIsNull(FieldCounterpartyID))
}

// CounterpartyIDNotNil applies the NotNil predicate on the "counterparty_id" field.
func CounterpartyIDNotNil() predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotNull(FieldCounterpartyID))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldContainsFold(FieldReason, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StockMovement {
	return predicate.StockMovement(sql.FieldLTE(FieldCreatedAt, v))
}

// HasWarehouse applies the HasEdge predicate on the "warehouse" edge.
func HasWarehouse() predicate.StockMovement {
	return predicate.StockMovement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WarehouseTable, WarehouseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWarehouseWith applies the HasEdge predicate on the "warehouse" edge with a given conditions (other predicates).
func HasWarehouseWith(preds ...predicate.Warehouse) predicate.StockMovement {
	return predicate.StockMovement(func(s *sql.Selector) {
		step := newWarehouseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StockMovement) predicate.StockMovement {
	return predicate.StockMovement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StockMovement) predicate.StockMovement {
	return predicate.StockMovement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StockMovement) predicate.StockMovement {
	return predicate.StockMovement(sql.NotPredicates(p))
}
